### ISSUE TITLE
[Explanation] max_open_pit_context

### ISSUE THREAD

**Issue by zalseryani** [opensearch-project/OpenSearch#10142]
# search.max_open_pit_context

- Can anyone provide more explanation on this setting, as we faced the issue while creating many PITs during the search? 
- What is the impact of this feature if many PIT has been created? 

I really appreciate any help you can provide.

**Comment by bharath-techie** [comment]
> Can anyone provide more explanation on this setting, as we faced the issue while creating many PITs during the search?
This setting defines the maximum number of active PIT reader contexts in the node , since each PIT context has a resource cost attached to it. 

>What is the impact of this feature if many PIT has been created?

If the open PIT readers piles up, then there is a big impact on disk space as the older segments will be referenced by PIT contexts. Also there is a chance of OOM because of too many open resources.
