### ISSUE TITLE
Enable doc_values based searching across different field types

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/OpenSearch#11205]
**Is your feature request related to a problem? Please describe.**
While working on #11097 i realized that MultiTerm queries over `Boolean` fields in OpenSearch don't support doc_values. I also noticed that the [documentation](https://opensearch.org/docs/latest/field-types/supported-field-types/boolean/) is incorrect and that booleans have doc_values enabled by default.

This is prevalent across multiple field types, there is a fix going out in #11144 to fix this for IP fields, I would also like to do this for other fields:
 - Date field -- https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java#L467
 - Geo Point - https://github.com/opensearch-project/OpenSearch/blob/10d34beb85ebee0a6bf36afece16e4ed991de641/server/src/main/java/org/opensearch/index/mapper/GeoPointFieldMapper.java#L239C9-L239C9
 - Geo Shape - https://github.com/opensearch-project/OpenSearch/blob/10d34beb85ebee0a6bf36afece16e4ed991de641/server/src/main/java/org/opensearch/index/query/VectorGeoShapeQueryProcessor.java#L84

**Describe the solution you'd like**
Since boolean fields type extends `TermBasedFieldType` we should probably override the `termQuery` and `termsQuery` functions and add support for doc_values queries. While we're at it, we should also add `IndexOrDocValuesQuery` to the range query. This will help use-cases where we have a range on a boolean field matching a lot of values.

**Describe alternatives you've considered**
Alternative is to do nothing. This is obviously bad since users will miss out on doc_values based queries that can improve performance.

**Additional context**
N/A

**Comment by kiranprakash154** [comment]
Hi, are we on track for this to be released in 2.12 ?

**Comment by msfroh** [comment]
Note that for Boolean fields, we might not see much benefit from a performance standpoint for indexed fields (since we have an efficient `advance` implementation for term queries and multiterm query expansion isn't going to expand beyond two terms).

That said, for consistency, now that we're supporting DV-only queries on many field types (including keyword, where Boolean is essentially a very restricted subcase of a keyword field), I like the idea that any field with doc values can support a (maybe slow) DV-only query.
