### ISSUE TITLE
[BUG] Incompatibility with elasticsearch-ruby 7.14

### ISSUE THREAD

**Issue by Venthe** [opensearch-project/OpenSearch#1166]
**Description**
Problem is occuring on opensearch:1.0.0 dockerfile
After setting compatibility as described [here](https://opensearch.org/docs/clients/agents-and-ingestion-tools/index/)

```json
{
  "persistent": {
    "compatibility": {
      "override_main_response_version": true
    }
  }
}
```

OpenSearch returns response which is invalid for ElasticSearch clients. Differences that I've found are:
* [Lack of `x-elastic-product: Elasticsearch` header](https://github.com/elastic/elasticsearch-ruby/blob/7.14/elasticsearch/lib/elasticsearch.rb#L73)
* [Mismatched `.tagline`:](https://github.com/elastic/elasticsearch-ruby/blob/7.14/elasticsearch/lib/elasticsearch.rb#L84) `The OpenSearch Project: https://opensearch.org/` vs `You Know, for Search`  NOT VERIFIED
* [Unset `.version.build_flavor: default`](https://github.com/elastic/elasticsearch-ruby/blob/7.14/elasticsearch/lib/elasticsearch.rb#L85) NOT VERIFIED

I've managed to get up until tagline check; before I've yielded.

**Repro**
Included minimal env, run `setup.sh` then observe the logs for the fluentd
[logging2 - Copy.zip](https://github.com/opensearch-project/OpenSearch/files/7070844/logging2.-.Copy.zip)

**Refs**
* Reference: https://github.com/uken/fluent-plugin-elasticsearch/issues/915

**Comment by dblock** [comment]
These checks were added in https://github.com/elastic/elasticsearch-ruby/pull/1360, similar to https://github.com/elastic/elasticsearch-py/pull/1623 and many others.

The `override_main_response_version` option in OpenSearch was introduced to support clients that worked previously against ES 7.10.2, the last OSS version, but elasticsearch-ruby 7.14 no longer does, so this won't be fixed in OpenSearch. It doesn't make much sense to keep chasing a moving target of more and more checks added in proprietary, not open-source, client libraries. 

Expect an opensearch-ruby release soon. It will work against ES and OpenSearch, and hopefully we can continue maintaining that compatibility in the future with community help. You can read more about this [here](https://opensearch.org/blog/community/2021/08/community-clients/). 

I'll close this, but please feel free to ask more questions!

**Comment by cosmo0920** [comment]
Hi @dblock,
Sorry for posting on the graveyard.

I'm a one of the fluent-plugin-elasticsearch plugin maintainer.
I have a question for this issue.

I know elasticsearch-ruby client added an incompatible change for OpenSearch.
But there is no compatible forked Ruby client OpenSearch.
fluent-plugin-elasticsearch heavily depends on its ruby client.

It would be nice to publish forked or the brand new Ruby client for OpenSearch on rubygems.

If "the client gem" is released, we can create Fluentd plugin for OpenSearch.

We don't like to use an old fixed version of elasticsearch-ruby client on OpenSearch Fluentd plugin.
