### ISSUE TITLE
Pagination and filters of index alias does not work.

### ISSUE THREAD

**Issue by ctellechea2001** [opensearch-project/OpenSearch#11660]
### Describe the bug

When you send a sql query to an Alias, that include non-zero fetch_size or has a filter an error happens.
Everything is OK if you query directly to the index.

`{
    "error": {
        "details": "Index type [alias_phrases] does not exist",
        "reason": "There was internal problem at backend",
        "type": "IllegalArgumentException"
    },
    "status": 500
}`

### Related component

Plugins

### To Reproduce

- Create an Index - indexA -- and load data
- Create an Alias - aliasA -- for the index
- Send query by devTools like: `select * from aliasA` with non-zero ("fetch_size": 50)
- Send query by devTools like: `select * from aliasA` including any filter ("filter": {any filter})
`{
    "error": {
        "details": "Index type [aliasA] does not exist",
        "reason": "There was internal problem at backend",
        "type": "IllegalArgumentException"
    },
    "status": 500
}`

### Expected behavior

The same result sending query to Alias o directly to the Indexes to support de rollover policies.

### Additional Details

https://github.com/opensearch-project/sql/issues/1398

Opensearch version tested: 2.7

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/dbwiddis) [3](https://github.com/andrross) [4](https://github.com/reta)]
@ctellechea2001 Thanks for creating this issue; however, it isn't being accepted due to not being clear that this isn't an issue in the sql plugin - please update the description to reproduce the issue in terms of OpenSearch core codebase. Please feel free to re-open after addressing the reason.

**Comment by ctellechea2001** [comment]
@peternied That is the same issue that was reported in this issue: https://github.com/opensearch-project/sql/issues/1398, reported by MaxKsyunz. In this ticket I have asked but I didn't received any answer.
