### ISSUE TITLE
How to fix security vulnerabilities in opensearch

### ISSUE THREAD

**Issue by smallemployees** [opensearch-project/OpenSearch#11738]
### Describe the bug

SSL/TLS server instantaneous Diffie Hellman public key too weak [principle scan]

### Related component

Other

### To Reproduce

Scan the corresponding port with security tools

### Expected behavior

After repair, it can be scanned

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/lukas-vlcek/)]
@smallemployees Thanks for creating this issue; however, it isn't being accepted due to it isn't clear how to reproduce this error or what is not secure. Please feel free to re-open after addressing the reason.
