### ISSUE TITLE
Working set computation for warm shard

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/OpenSearch#11793]
### Is your feature request related to a problem? Please describe

For each warm shard, we want to evaluate a initial set of blocks to prefetch to optimize the read/write operations on the shard. 

### Describe the solution you'd like

TBD

### Related component

Storage:Remote

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/macohen) [4](https://github.com/jainankitk)]
Thanks for creating this issue; however, it isn't being accepted due to being too vague could you add more details? Please feel free to re-open after addressing the reason
