### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by CCTV-six** [opensearch-project/OpenSearch#11919]
### Describe the bug

When the OpenSearch high availability cluster rebalances data, it is found that the data between nodes is inconsistent
Error: Inconsistent data found in cluster during rebalance: node1 has 100 documents, node2 has 90.

### Related component

Clients

### To Reproduce

Inconsistent data writing: Ensure that all nodes can correctly receive and store data when writing to the OpenSearch cluster.

Network partition or node failure: Simulate network partition or node failure, causing data synchronization interruption.

Configuration error or inconsistency: Check the configuration of the OpenSearch cluster to ensure that all nodes have the same and correct configuration

### Expected behavior

The root cause of the problem is diagnosed as inconsistent data writing, network failure, or configuration error.

### Additional Details

none

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/lukas-vlcek/)]
@CCTV-six Thanks for creating this issue; however, it isn't being accepted due to being unclear on specifically what needs to be addressed - providing a integration test that illustrates the issue with rebalancing would clarify. Please feel free to re-open after addressing the reason.
