### ISSUE TITLE
[Tiered Caching][Milestone 1] Expose a cache type setting and integrate it with IndicesRequestCache

### ISSUE THREAD

**Issue by sgup432** [opensearch-project/OpenSearch#11947]
### Is your feature request related to a problem? Please describe

Tracked as part of https://github.com/opensearch-project/OpenSearch/issues/10870

As part of this, we want to expose a cache type setting with onHeap as a start. Tiered option would be added later once desired changes are in.

User can define cache type setting for IndicesRequestCache as a start.

### Describe the solution you'd like

Solution being tracked as part of PR.

### Related component

Storage:Performance

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/lukas-vlcek/) [3](https://github.com/rbowen)]
@sgup432 Thanks for creating this issue; however, it isn't being accepted due to that the purpose and the outcome of this issue isn't clear. Please feel free to re-open after addressing the reason.
