### ISSUE TITLE
[Feature Request] [Metrics Framework] Add support for Histogram to record the latency metrics.

### ISSUE THREAD

**Issue by Gaganjuneja** [opensearch-project/OpenSearch#12061]
### Is your feature request related to a problem? Please describe

As part of the [issue](https://github.com/opensearch-project/OpenSearch/issues/10238) we have added the Metrics Framework and support for just the counter type of metrics. We also need to add Histogram support to record the latency metrics also.

### Describe the solution you'd like

We have discussed in the [RFC](https://github.com/opensearch-project/OpenSearch/issues/10141) on the API contract and how it will be implemented. 

### Related component

Libraries

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/lukas-vlcek/) [3](https://github.com/andrross) [4](https://github.com/CEHENKLE) [5](https://github.com/dbwiddis) [6](https://github.com/reta/) [7](https://github.com/anasalkouz) [8](https://github.com/aggarwalShivani)]
@Gaganjuneja Thanks for creating this issue; however, it isn't being accepted due to not having a clear outcome, while you've reference the RFC this issue should include details around the solution that are part of the pull request. Please feel free to re-open after addressing the reason.
