### ISSUE TITLE
[Feature Request] Re-design the sharding strategy

### ISSUE THREAD

**Issue by riysaxen-amzn** [opensearch-project/OpenSearch#12147]
### Is your feature request related to a problem? Please describe

By default, system index settings are set to auto_expand_replicas to `0-all` and number of primary shards to 5. This is causing the issues like single node cluster turning yellow after configuring plugins, increase in JVM pressure

### Describe the solution you'd like

RE-design of sharding strategy

### Related component

Plugins

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/dbwiddis) [3](https://github.com/andrross) [4](https://github.com/reta)]
@riysaxen-amzn Thanks for creating this issue; however, it isn't being accepted due to it being unclear why this is an issue, as cluster operators can change defaults. Please feel free to re-open after addressing the reason.
