### ISSUE TITLE
Refactor RemoteStoreRefreshListenerTests to use listener from IndexShard

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#12160]
### Is your feature request related to a problem? Please describe

https://github.com/opensearch-project/OpenSearch/pull/12157#discussion_r1477719763

### Describe the solution you'd like

Test should use RemoteStoreRefreshListener instance from IndexShard

### Related component

Storage:Durability

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/dbwiddis) [3](https://github.com/andrross) [4](https://github.com/reta)]
@sachinpkale Thanks for creating this issue; however, it isn't being accepted due to not having enough details in this issue. Please feel free to re-open after addressing the reason.
