### ISSUE TITLE
[Feature Request] Latency metrics in AllocationService

### ISSUE THREAD

**Issue by Pranshu-S** [opensearch-project/OpenSearch#12363]
### Is your feature request related to a problem? Please describe

Currently, there's no efficient way to track the latency of reroute actions in the allocation service of OpenSearch. This lack of visibility hinders the ability to identify and address performance issues effectively. Introducing latency metrics would provide crucial insights into the allocation process, enabling us to optimize performance and enhance overall system efficiency.

### Describe the solution you'd like

Support for Histogram type metrics.

### Related component

Cluster Manager

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/dbwiddis) [3](https://github.com/lukas-vlcek) [4](https://github.com/kotwanikunal) [5](https://github.com/linuxpi)]
@Pranshu-S Thanks for creating this issue; however, it isn't being accepted due to not having a clear solution, please add much more detail on what kind of metric and how it applies to the problem described. Please feel free to open a new issue after addressing the reason.
