### ISSUE TITLE
[Feature Request] Pipeline ingest processor supports ignoring the non-existing pipeline

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/OpenSearch#12463]
### Is your feature request related to a problem? Please describe

Now the pipeline ingest processor always throws exception `Pipeline processor configured for non-existent pipeline [non-existen]` if the specified pipeline doesn't exist:
```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "pipeline": {
          "name" : "non-existen"
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "foo": "bar"
      }
    }
  ]
}
```

### Describe the solution you'd like

The pipeline ingest processor supports a parameter like` ignore_missing`, when the specified pipeline doesn't exist and the parameter is set to true, the processor exit quietly.

### Related component

Indexing

### Describe alternatives you've considered

No alternatives.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/lukas-vlcek/) [4](https://github.com/srikanthpadakanti) [5](https://github.com/Mahima081)]
@gaobinlong Thanks for creating this issue; however, it isn't being accepted due to this making the outcome of this request non-deterministic. Please feel free to open a new issue after addressing the reason.

@msfroh Do you have additional thoughts?
