### ISSUE TITLE
When the VM memory usage reaches around 80%, GC recycling will occur, but it will trigger a JVM memory usage alarm. Is there any optimization method?

### ISSUE THREAD

**Issue by smallemployees** [opensearch-project/OpenSearch#12535]
### Is your feature request related to a problem? Please describe

Is there a way to locate or optimize the dynamic pattern recycling of OpenSearch's JVM, which constantly triggers my warning strategy?

### Describe the solution you'd like

Release this cycle of alarms by adjusting thresholds or other strategies

### Related component

Cluster Manager

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/RasonJ) [3](https://github.com/dbwiddis) [4](https://github.com/kotwanikunal) [5](https://github.com/Mahima081)]
@smallemployees Thanks for creating this issue; however, it isn't being accepted due to not having clear details to reproduce or if this is a bug.

This seems more like question for how to operate / configure OpenSearch, we would recommend checking out the forums [1] for more details/help in this area. 

- [1] https://forum.opensearch.org/
