### ISSUE TITLE
[BUG] Flaky test :qa:mixed-cluster:v2.14.0#mixedClusterTest related to indices.stats

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/OpenSearch#12980]
### Describe the bug

Multiple tests for [org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT](https://build.ci.opensearch.org/job/gradle-check/36125/testReport/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_indices_stats_13_fields_Completion___pattern_/) are failing with below error in cluster stdout. 
```
{
            "shard" : 0,
            "index" : "test1",
            "status" : "INTERNAL_SERVER_ERROR",
            "reason" : {
              "type" : "failed_node_exception",
              "reason" : "Failed node [_o1G3w2eSd6aJ4vuTuJGlw]",
              "node_id" : "_o1G3w2eSd6aJ4vuTuJGlw",
              "caused_by" : {
                "type" : "transport_serialization_exception",
                "reason" : "Failed to deserialize response from handler [org.opensearch.transport.TransportService$ContextRestoreResponseHandler/org.opensearch.transport.TransportService$9/[indices:monitor/stats[n]]:org.opensearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction$1@6cf2683f]",
                "caused_by" : {
                  "type" : "illegal_state_exception",
                  "reason" : "unexpected byte [0x80]"
```

### Related component

Other

### To Reproduce

See list of all failing tests here https://build.ci.opensearch.org/job/gradle-check/36125/testReport/

### Expected behavior

Tests should pass.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/lukas-vlcek) [2](https://github.com/cwperks) [3](https://github.com/jed326) [4](https://github.com/scrawfor99) [5](https://github.com/kotwanikunal) [6](https://github.com/srikanthpadakanti) [7](https://github.com/peternied) [8](https://github.com/andrross)]
@rishabh6788 Thanks for filing, it looks like this was a temporary issue that has been resolved (otherwise all PRs would be blocked).  Closing this out.
