### ISSUE TITLE
[Remote Routing Table] Create Service for remote routing table storage

### ISSUE THREAD

**Issue by himshikha** [opensearch-project/OpenSearch#13049]
### Is your feature request related to a problem? Please describe

Create a RemoteClusterStateService which would orchestrate the upload to blob storage. This service would be similar to [RemoteClusterStateService](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java)

Meta issue: https://github.com/opensearch-project/OpenSearch/issues/12995

### Related component

ShardManagement:Routing

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/lukas-vlcek) [2](https://github.com/cwperks) [3](https://github.com/jed326) [4](https://github.com/scrawfor99) [5](https://github.com/kotwanikunal) [6](https://github.com/srikanthpadakanti) [7](https://github.com/peternied) [8](https://github.com/andrross)]
@himshikha Thanks for creating this issue; however, it isn't being accepted due to not having enough detail on why the change should be made nor the impact when it is resolved. Please feel free to open a new issue after addressing the reason.
