### ISSUE TITLE
[Feature Request] Add RetryableListener in opensearch core

### ISSUE THREAD

**Issue by zane-neo** [opensearch-project/OpenSearch#13132]
### Is your feature request related to a problem? Please describe

Currently there're cases that using [NodeClient](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/client/node/NodeClient.java) to dispatch requests to other nodes to execute. But it's possible that the node been dispatched crash during processing the request, and user will get exception. In a large cluster, such random node failure is pretty normal and the exception can be a considerable inconvenient for user.
In opensearch core, we have [RetryableAction](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/support/RetryableAction.java) and [RetryableTransportClient](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/recovery/RetryableTransportClient.java) but the Action is designed to an abstract class so many cases a transportAction can not extend it if it has to extends another class. The [RetryListener](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/reindex/RetryListener.java) seems to have a dedicated purpose and not generic.

### Describe the solution you'd like

We can create a new RetryableListener in opensearch core, and when retry is necessary we can use this actionListener directly or override some methods in it, e.g. `shouldRetry` and `retryFunction` so the retry can be performed by leveraging these methods.

### Related component

Other

**Comment by lukas-vlcek** [comment]
@zane-neo Out of curiosity, can you give an example of operations or scenarios where you experience failures and would benefit from automatic retry? I am trying to understand specific use cases.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/vikasvb90
) [4](https://github.com/andrross
) [5](https://github.com/lukas-vlcek/
) [6](https://github.com/srikanthpadakanti)]
@zane-neo Thanks for creating this issue; however, it isn't being accepted due to not being specific on the scenarios that are occurring to justify this retry logic - we'd need more context to reason if it should be accepted or not. Please feel free to open a new issue after addressing the reason.

**Comment by zane-neo** [comment]
Created this issue: https://github.com/opensearch-project/OpenSearch/issues/13157
