### ISSUE TITLE
[BUG] Error or Delay when collecting log from Grafana

### ISSUE THREAD

**Issue by zinho9** [opensearch-project/OpenSearch#13189]
### Describe the bug

Hello, I am try to collect log from opesearch at Grafana.

The whole logic is right this.

Make Alert rules in Grafana -> Datasource : Opensearch
Query : event.original : "xxxxxxxxxx"

And then, I am tried to use Group By for parsing my alert.
But there are some problems while using Group by.

Some of Group By options are not available.
Error message is right this
```
Failed to evaluate queries and expressions: [plugin.downstreamError] failed to query data: Failed to query data: rpc error: code = DeadlineExceeded desc =context deadline exceeded
```

Not all of Group By options are not available but some of them are problem.
I have to use event.original.keyword or msgbody.keyword but both of them are not available.
Hostname.keyword is available.

Please help me what I am missing.

Grafana version  : 10.0.0.2
Opensearch plugin version in Grafana : 2.14.4
Opensearch version : 2.11

### Related component

Search

### To Reproduce

x

### Expected behavior

x

### Additional Details

![KakaoTalk_Snapshot_20240415_165331](https://github.com/opensearch-project/OpenSearch/assets/65962383/ea27fa45-9b80-4765-aabd-44923382b43e)
**Screenshots**

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/vikasvb90/) [2](https://github.com/reta/) [3](https://github.com/scrawfor99) [4](https://github.com/jed326) [5](https://github.com/kotwanikunal) [6](https://github.com/peternied) [7](https://github.com/lukas-vlcek/)]
@zinho9 Thanks for creating this issue; however, it isn't being accepted due to not having clear indication that the problem is within OpenSearch - it looks like this is an issue with Grafana's system.  We would accept a bug reports that show incorrect responses from the OpenSearch cluster.   Please feel free to open a new issue after addressing the reason.
