### ISSUE TITLE
OpenSearch encountered a mapping parsing exception while creating an index

### ISSUE THREAD

**Issue by CCTV-six** [opensearch-project/OpenSearch#13379]
### Describe the bug

org.opensearch.index.mapper.MapperParsingException: Failed to parse mapping [my_index]: Root mapping definition has unsupported parameters:  [my_custom_field : {type=keyword}]

### Related component

Indexing

### To Reproduce

none

### Expected behavior

Can smoothly create or update indexes without mapping parsing exceptions

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by mgodwan** [comment]
Could you please share the steps to reproduce i.e. the API call, payload, OpenSearch version, etc,?

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/kotwanikunal) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/jed326) [6](https://github.com/dbwiddis) [7](https://github.com/srikanthpadakanti) [8](https://github.com/hasnain2808)]
@CCTV-six Thanks for creating this issue; however, it isn't being accepted due to not being clear there is an issue with the feature, please include reproduction steps and details as to why an error response shouldn't be expected. Please feel free to open a new issue after addressing the reason."
