### ISSUE TITLE
[Tiering] API contract for status API 

### ISSUE THREAD

**Issue by neetikasinghal** [opensearch-project/OpenSearch#13395]
### Is your feature request related to a problem? Please describe

Come up with the API contract for status api for index under-going tiering.

### Describe the solution you'd like

API, request, response, failure cases.

### Related issues

#13294

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/kotwanikunal) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/jed326) [6](https://github.com/dbwiddis) [7](https://github.com/srikanthpadakanti) [8](https://github.com/hasnain2808)]
@neetikasinghal Thanks for creating this issue; however, it isn't being accepted due to this issue doesn't have enough detail for anyone else to implement or verify a related pull request. Please feel free to open a new issue after addressing the reason."
