### ISSUE TITLE
[Feature Request] Add more ITs around tiered caching stats

### ISSUE THREAD

**Issue by peteralfonsi** [opensearch-project/OpenSearch#13455]
### Is your feature request related to a problem? Please describe

As part of tiered caching we have added [a new cache stats API](https://github.com/opensearch-project/OpenSearch/issues/12258), where individual ICache implementations keep track of their own stats. This approach makes it easier to plug in new cache implementations. We have some ITs around this, but we should add more to make sure there aren't any unknown issues. 

### Describe the solution you'd like

We should add more ITs combining different cache types with different level aggregations for the stats, across a wider variety of clusters. 

### Related component

Search:Performance

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/kotwanikunal) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/jed326) [6](https://github.com/dbwiddis) [7](https://github.com/srikanthpadakanti) [8](https://github.com/hasnain2808)]
@peteralfonsi Thanks for creating this issue, looking forward to a pull request.

In the future when creating issues, could you include the specific tests that are missing so its clearer to know when this issue is resolved?
