### ISSUE TITLE
[BUG] Unknown aggregation type [cumulative_cardinality]

### ISSUE THREAD

**Issue by tushar-koshti** [opensearch-project/OpenSearch#13659]
### Describe the bug

I'm not able to use [cumulative_cardinality](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-cumulative-cardinality-aggregation.html) aggregation in Opensearch

### Related component

Search:Aggregations

### Expected behavior

It should provide the response as per aggregation

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/vikasvb90/) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/reta/) [6](https://github.com/dbwiddis) [7](https://github.com/cwperks) [8](https://github.com/lukas-vlcek/)]
@tushar-koshti Thanks for creating this issue; however, it isn't being accepted due to not having clear reproduction steps - doesn't seem like a bug. Please feel free to open a new issue after addressing the reason.

It looks like this is a support focused question, please use https://forum.opensearch.org/ for help using features.

**Comment by andrross** [comment]
@tushar-koshti Feel free to open a feature request issue if you'd like to have support for a new aggregation, but please be specific about what problem you're trying to solve.

**Comment by getsaurabh02** [comment]
Cumulative cardinality aggregation are not supported as of yet in OS. You can open a feature request with use cases that you would like to get supported.
