### ISSUE TITLE
500 error using _render/template

### ISSUE THREAD

**Issue by slylock** [opensearch-project/OpenSearch#13651]
### Describe the bug

After upgrading from 2.7 to 2.11, use of the _render/template api returns a 500 error, even though I'm logged in to Dev Tools with a user that has * * permission (all_access role).

Example POST (or GET, either one returns error):
POST _render/template/my_search_template
{
  "params": {
			"my_param": "hello",...

Error:
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "Unexpected exception indices:data/read/search/template"
      }
    ],
    "type": "security_exception",
    "reason": "Unexpected exception indices:data/read/search/template"
  },
  "status": 500
}

### Related component

Search

### To Reproduce

GET _render/template/my_search_template
{
  "params": {
			"my_param": "hello",...

### Expected behavior

Should return rendered template, but gives 500 error.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by slylock** [comment]
Looks to be a duplicate of #3672

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/vikasvb90/) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/reta/) [6](https://github.com/dbwiddis) [7](https://github.com/cwperks) [8](https://github.com/lukas-vlcek/)]
@slylock Thanks for creating this issue - that linked item looks to be merged, has this been fixed in a newer version?

**Comment by cwperks** [comment]
@slylock This is a known issue in 2.11.x.

A fix was released in 2.12.0: https://github.com/opensearch-project/OpenSearch/pull/11170
