### ISSUE TITLE
Opensearch initialization process missing index

### ISSUE THREAD

**Issue by smallemployees** [opensearch-project/OpenSearch#13680]
### Describe the bug

If there is an exception during the initialization process that causes the system index creation to fail, restarting will execute the initialization step code again

### Related component

Other

### Expected behavior

How can I fix the missing index situation

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by dblock** [comment]
@smallemployees AFAIK this is the expected behavior. Could you please describe why this is a problem, and maybe provide repro steps?

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/vikasvb90/) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/reta/) [6](https://github.com/dbwiddis) [7](https://github.com/cwperks) [8](https://github.com/lukas-vlcek/)]
@smallemployees Thanks for creating this issue; however, it isn't being accepted due to not having clear reproduction steps and expectations. Please feel free to open a new issue after addressing the reason.

**Comment by cwperks** [comment]
@smallemployees What error message are you receiving on bootstrap?

If the high watermark is exceeded (disk space is full) it can fail to create indices.
