### ISSUE TITLE
Want to add Hanlp and other Chinese word segmentation official plug-in

### ISSUE THREAD

**Issue by kxleee** [opensearch-project/OpenSearch#13987]
### Is your feature request related to a problem? Please describe

At present, the use of the latest opensearch has to manually adapt hanlp and other Chinese word segmentation plug-ins, time-consuming and laborious, hope to get official support

### Describe the solution you'd like

hanlp Chinese word segmentation official plug-in with official support

### Related component

Plugins

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/srikanthpadakanti) [2](https://github.com/peternied) [3](https://github.com/lukas-vlcek) [4](https://github.com/jed326) [5](https://github.com/reta) [6](https://github.com/andrross) [7](https://github.com/kotwanikunal)]
@kxleee Could you please provide more detail about the what is not supported / not working.  It is not clear what action you'd like OpenSearch to take to support (?) or enable (?) these scenarios.

FYI @elfisher Do you know if we have someone on language support that can check in on this?

**Comment by dblock** [comment]
@kxleee Are you referring to https://github.com/pgtgrly/opensearch-analysis-hanlp? It would be great if someone contributed CI/CD to that plugin so it can build and release regularly with OpenSearch, before we discuss moving it into this org and including it in the official distribution.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/andrross) [4](https://github.com/jed326/) [5](https://github.com/akolarkunnu/)]
@kxleee We haven't seen a response - closing this issue out since it isn't actionable with out more details.  Please open a new issue with a specific request or an RFC for a discussion around a topic - thanks.
