### ISSUE TITLE
Modify ActionRequest in core to allow for resource_names to be passed in the request

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/OpenSearch#14751]
## Description

This base class is extended by every plugin’s implementation of transport request calls. Hence, the idea is to add a standard class property List<String> resources.  In addition, add `resource:` as a valid transport action prefix [here](https://github.com/opensearch-project/OpenSearch/blob/2069bd805804dd93bd69695a4c6521cc6f2b9bb6/server/src/main/java/org/opensearch/transport/TransportService.java#L1097).

This will then be implemented by plugins to populate this property when handling an actionRequest after which [SecurityFilter.java](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/filter/SecurityFilter.java) will intercept this call to perform privilege evaluation.

## Implementation

Coming from comment: https://github.com/opensearch-project/security/issues/4500#issuecomment-2204198581, we will proceed with approach a, which introduces a new getter for resources, there-by allowing request handlers in plugin to populate the resource names before sending the request to Transport layer. Here is the pseudo-code (thank you @nibix):

```java
public abstract class ActionRequest extends TransportRequest {

    public ActionRequest() {
        super();
    }

    public ActionRequest(StreamInput in) throws IOException {
        super(in);
    }
 
    /**
      * NEW NEW NEW .. to be overridden by whoever wants to
      */
    public List<String> getResources() {
       return Collections.emptyList();
    }

    public abstract ActionRequestValidationException validate();

    public boolean getShouldStoreResult() {
        return false;
    }

    @Override
    public void writeTo(StreamOutput out) throws IOException {
        super.writeTo(out);
    }
}
```

**Comment by nibix** [comment]
I mentioned it just briefly in https://github.com/opensearch-project/security/issues/4500#issuecomment-2204198581, but thought it might be worth pointing out more explicitly:

Instead of directly extending `ActionRequest`, one could also think about introducing a new interface which actions need to implement when they want to provide resource information. 

That would be consistent to the style so far. Examples for this are:

- https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/IndicesRequest.java
- https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/CompositeIndicesRequest.java
- https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/AliasesRequest.java
- https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/RealtimeRequest.java

This helps to keep the `ActionRequest` class terse.

It could look similar to this:

```
interface PluginResourceRequest {
   List<String> getResources();
}
```

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/jed326) [3](https://github.com/reta)]
@DarshitChanpura Thanks for creating this issue; however, it isn't being accepted due to not having a clear problem that is trying to be solved.

If we had a model for defining addresses of resources, those could be useful for identifying and permission items, but it isn't clear if this issue would follow those needs.  A list of untyped strings seems like it would create future issue without other infrastructure built up around it.

Please feel free to open a new issue after addressing the reason.
