### ISSUE TITLE
Update Segment replication stats APIs to support pull based architecture

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#15534]
With #4577 replicas will sync directly with their source of replication rather than pushing updates from the primary.

Today stats are collected at the primary level to support APIs and enforce backpressure.  With the rw split we will ensure primaries do not have any direct communication with replicas and will not be able to collect these stats.

To fix this we can update our stats APIs to fetch the latest checkpoint from each replica directly and compute the required stats at the coordinator, eliminating the need for primaries to capture these stats.

**Comment by vinaykpud** [comment]
Hi @mch2 can I take this task?

**Comment by vinaykpud** [comment]
Documentation for the current CAT SegRep Stats API:
https://opensearch.org/docs/latest/api-reference/cat/cat-segment-replication/

I tried to explain how the this API work currently bellow:

Currently each replica once the replication is complete for the latest received checkpoint it updates the visible checkpoint to the primary shard. Primary keeps track of all the checkpoints replicated at the replicas. Whenever stats is requested primary calculates the stats using the tracked replica checkpoints. The algorithms for this API work like bellow:

> Steps:

1. Request received at the coordinator it will broadcast the request to all the nodes. 
2. Request will be executed in all the shards in the nodes. 
      1. If its primary node it builds and returns the `SegmentReplicationPerGroupStats`. As part of this it computes the stats of all of its replica ie `SegmentReplicationShardStats` per replica.
      2. If its Replica node it returns the `SegmentReplicationState` 
3. Response is collected at the coordinator. `SegmentReplicationState` received from the replica shards used to
enrich the `SegmentReplicationShardStats` calculated at the primary.
4. Coordinator returns the combined response

> How the replication works for the regular replica?

Primary Shard publishes the the checkpoint. All the replica shards will receive the checkpoint. Once replica receives the checkpoint it starts replication process for that checkpoint. Once the replication is complete replica updates latestVisibleCheckpoint the primary.

> How the replication works for the search replica?

For search replicas, it runs an async process continuously for every interval ie default 1s. Job of the async process is to startReplication from the `SegmentReplicationSource` as Remote store. So it will fetch the checkPoint from the remote store and perform the replication.

With the addition of the search replica, we cannot continue to calculate the SegRep stats how we do now. Because with the reader/writer split we ensure that primaries do not have any direct communication with replicas ie Primary do not aware of the Search replica checkpoints. So we have to calculate the stats for the search replica differently.

> Lets now check different metrics we return as part of the response:

_`CheckPointBehindCount`_: Number of checkpoints by which replica is behind the primary shard.

_`BytesBehindCount`_: Number of bytes by which replica is behind the primary shard.

_`CurrentReplicationLag`_: The time elapsed while waiting for a replica shard to catch up to the primary shard.
 
_`LastCompletedReplicationLag`_: The time taken for a replica shard to catch up to the latest primary shard refresh.

_`RejectedRequests`_: The number of rejected requests for the replication group.


> Lets now check how the SegRep Stats metric calculation logic works now

Currently the calculation happens in `ReplicationTracker`, This requires three different important data,

1. VisibleCheckPoint at the shard
    1. Checkpoint which is shard has most recently computed
2. LatestReplicationCheckpoint 
    1. Latest checkpoint at the primary shard
3. SegmentReplicationLagTimer 
    1. It has two different values. CreationTime and StartTime.
    2. Timer created when the checkpoint created/refreshed at the primary and started when the checkpoint is published

* _`CheckPointBehindCount`_ is calculated based on the active checkpoint timers
* VisibleCheckPoint and LatestReplicationCheckpoint are used to calculate the _`BytesBehindCount`_ which says how far behind the replica from primary. 
* _`CurrentReplicationLag`_ is calculated based on the SegmentReplicationLagTimer
* _`LastCompletedReplicationLag`_ is the last completed replication time tracked by `ReplicationTracker`
* _`RejectedRequests`_ is the metric which is from pressure service


As above section provides some detailed background on this issue, In the following comment I will add the proposed solution details

**Comment by vinaykpud** [comment]
### Solution 1:

We will keep the current way of calculation for the regular replicas, but start supporting the search replicas also in the stats.

This can be achieved by calculating and returning the stats from the search replica shard and using that in the coordinator to enrich the overall stats to include the search replica stats as well.

Pros:

* No changes in the existing way of calculation for regular replica

Cons:

* Stats calculated for search replica doest compare it with the checkpoint in primary shard.
* Stats calculated differently for the search replica, so this will change the definition or meaning of the metrics for search replica. 
* Since we present the data of regular replica and search replica together in the response user may get confused with the difference in the meaning of this metrics

> Deep dive:

We need to calculate the SegmentReplicationShardStats for the search replica shard individually. 

So for CheckPointBehindCount and BytesBehindCount calculation we can use latestReplicationCheckpoint at the shard and latestReplicationCheckpoint consumed by the replication process. This will actually give the replication lag with respective to the latest received checkpoint. 

For CurrentReplicationLag and LastCompletedReplicationLag calculation we can use the timer available in the SegmentReplicationState

In the coordinator node, we can use the SegmentReplicationShardStats from the search replica to enrich the existing stats thats computed from regular replicas.

**Comment by vinaykpud** [comment]
### Solution 2:

We can calculate the stats at the replicas and return those stats to coordinator. Coordinator will combine all the stats received from the replicas.

Pros:

* We can unify the metrics meaning and definition irrespective of the replica types.

Cons:

* This will change the overall definition of the stats published as part of this which is a major change for the API.
* We wont be comparing the checkpoints between the primary and replica’s anymore. So we wont know the answer for “how far the replica behind the primary”

> Deep dive :

We need to calculate the `SegmentReplicationShardStats` for the search replica shard and regular replica shard individually without referencing the primaryShard. 

So for _CheckPointBehindCount_ and _BytesBehindCount_ calculation we can use `latestReplicationCheckpoint` at the shard and `latestReplicationCheckpoint` consumed by the replication process. This will actually give the replication lag with respective to the latest received checkpoint.  

For _CurrentReplicationLag_ and _LastCompletedReplicationLag_ calculation we can use the timer available in the `SegmentReplicationState`

Once every replica shard returns the `SegmentReplicationShardStats`, this can be combined as a Set in the coordinator node. 

`SegmentReplicationPerGroupStats` for the index can be created in the coordinator node using the replica shard stats. 

_rejectionCount_ cannot be computed as it comes from the pressure service or we can return this data from the primary shard and use this in the coordinator.

_rejectionCount_ is not applicable for the search replicas.

> Proposed Metrics definition :

_CheckPointBehindCount_: Number of checkpoints by which replica is behind with respective to the latest received checkpoint in the replica.

_BytesBehindCount_: Number of bytes by which replica is behind with respective to the latest received checkpoint in the replica.

_CurrentReplicationLag_: Total time elapsed for the replica shard to perform the current segment replication.
 
_LastCompletedReplicationLag_: Total time elapsed for replica shard to complete the last replication.

**Comment by vinaykpud** [comment]
### Solution 3:

We can fetch the latest visible checkpoints from each replica and compute the required stats at the coordinator. 

We need to compare the `latestReplicationCheckpoint` from primary against the checkpoints received from each replica to build the metrics.

Pros:

* We still be comparing the replicas against the primary to get the metrics, which makes us in sync with the current definition of the API. We can know “how far the replica behind the primary”.

Cons:

* We will start using the `SegmentReplicationState` from the replicas to calculate the lag times, which will change the existing way of calculation.

#### Deep dive:

Every replica shard can keep track of the `latestVisibleCheckPoint` based on the segment replication completion.
Every replica shard will return its `latestVisibleCheckPoint` and `SegmentReplicationState`.

In the coordinator node, we have latestCheckPoint from the primary and latestVisibleCheckPoint from other shards.
Using this we can calculate set of `SegmentReplicationShardStats` for the replicas. 
Use the `SegmentReplicationState` to enrich the  `SegmentReplicationShardStats` of replica

`SegmentReplicationState` has overallTimer which is time taken for a single replication. `overallTimer.time()` will give the elapsed time for the replication. Similarly this will get the lastReplicationLag from the state using overallTimer.

Build `SegmentReplicationPerGroupStats` at the coordinator:

1. ShardId
2. Set of `SegmentReplicationShardStats` for the replicas
3. rejectionCount comes from the pressure service, so we may need to return this from the primary shard to use it here.

Return the overall response from the coordinator.

#### Proposed Metrics definition :

_CheckPointBehindCount_: Number of checkpoints by which replica is behind the primary shard.

_BytesBehindCount_: Number of bytes by which replica is behind the primary shard.

_CurrentReplicationLag_: Total time elapsed for the replica shard to perform the current segment replication.
 
_LastCompletedReplicationLag_: Total time elapsed for replica shard to complete the last replication.

**Comment by vinaykpud** [comment]
So in summary: 

Choosing between this options really depends on what are metrics we really care and how we want to interpret the meaning of metrics. 

* Solution 2 and Solution 3 unifies the meaning of the metrics between search and regular replica where as Solution 1 adds difference in the meaning depending on the replica type.
* Solution 3 provides a way to answer “how far the replica behind the primary”, where as Solution 2 takes away that and the calculates the stats without referring the primary shard checkpoint.
