### ISSUE TITLE
[Feature Request] Introduce a rescore search response processor

### ISSUE THREAD

**Issue by mingshl** [opensearch-project/OpenSearch#15631]
### Is your feature request related to a problem? Please describe

When a field with score is added by a response processor, we try to sort the response by the added field. 

 in the search response, there are multiple documents in hits. a rescore search response processor can take the score from a field from the document, and sort the search hits based on the field value. Users can opt to remove the field in the documents.  

### Describe the solution you'd like

The proposed solution as follows: 

```
PUT /_search/pipeline/my_pipeline
{
  "response_processors": [
    {
      "rescore": {
        "field": "similarity_score",
        "sort": "desc",
        "replace_score": true 
        "remove_sort_field" : true
      }
    }
  ]
}
```

for example:

```
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 4,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "diary_index",
        "_id": "1",
        "_score": 1,
        "_source": {
          "diary": "how are you",
          "similarity_score": -11.055182
        }
      },
      {
        "_index": "diary_index",
        "_id": "2",
        "_score": 1,
        "_source": {
          "diary": "today is sunny",
          "similarity_score": 8.969885
        }
      },
      {
        "_index": "diary_index",
        "_id": "3",
        "_score": 1,
        "_source": {
          "diary": "today is july fifth",
          "similarity_score": -5.736348
        }
      },
      {
        "_index": "diary_index",
        "_id": "4",
        "_score": 1,
        "_source": {
          "diary": "it is winter",
          "similarity_score": -10.045217
        }
      }
    ]
  }
}
```

the response after processing:

```
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 4,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [

{
        "_index": "diary_index",
        "_id": "2",
        "_score": 8.969885,
        "_source": {
          "diary": "today is sunny"
        }
      },
      {
        "_index": "diary_index",
        "_id": "3",
        "_score": -5.736348,
        "_source": {
          "diary": "today is july fifth"
        }
      },
      {
        "_index": "diary_index",
        "_id": "4",
        "_score": -10.045217,
        "_source": {
          "diary": "it is winter"
        }
      }
      , {
        "_index": "diary_index",
        "_id": "1",
        "_score": -11.055182,
        "_source": {
          "diary": "how are you"
        }
      }
    ]
  }
}
```

### Related component

Search

**Comment by mch2** [comment]
tagging @msfroh @martin-gaievski

**Comment by msfroh** [comment]
Makes sense -- if a field was added by response processor, the only way that you can really do something with it (before sending back to the client) is with another response processor.

With the ever-present "naming is hard" challenge, I'm not sure I like the name `rescore`. Maybe `sort`? Or `sort_by_field`?

**Comment by msfroh** [comment]
In theory, if we *really* wanted to get into the "do one thing" philosophy for search processors, then we could use the `remove_field` response processor to remove the field after sorting, rather than including it in this processor.

Similarly/alternatively, we could add a `copy` response processor that copies the field value into `_score`. (That could also be done with a shared `copy` document processor, if we ever get those.) Of course, the `copy` ingest processor already does two things by having the `remove_source` parameter.

**Comment by mingshl** [comment]
> Makes sense -- if a field was added by response processor, the only way that you can really do something with it (before sending back to the client) is with another response processor.
> 
> With the ever-present "naming is hard" challenge, I'm not sure I like the name `rescore`. Maybe `sort`? Or `sort_by_field`?

there is a sort response processor already, but it's sorting a array field in the document. 

yay, naming is hard. `sort_by_field` is straight forward but a bit long.

**Comment by brianf-aws** [comment]
Hey y'all, I would like to work on this feature! I like Rescore since its taking a already scored value e.g. `_score": 1`. The closest thing I can think of is `refineScore` as a name.

I have some questions I want to bring to the table:
1. What do we do with Tiebreakers? **Should we use First item in with same score to be shown earlier?**
2. How do we want to handle failure? **Should we just return the values that were given before hand?**
3. What are some ways that users can mishandle the processor? _I'm new to crafting processors but would like some context_

**Comment by brianf-aws** [comment]
Adding this [META GH enhacement for ML Inference](https://github.com/opensearch-project/ml-commons/issues/2878)

**Comment by brianf-aws** [comment]
I did some research and I think we might be able to leave out the sorting functionality as there exists a sort results functionality within OS core [you can see here ](https://opensearch.org/docs/latest/search-plugins/searching-data/sort/), this feature allows you to search within the search hits.

In essence this allows you to define a search pipeline with the rescore processor and then after you are done you could sort by the `_score` field. I feel that more discussion though.

Here is an example
```
GET /my-index/_search?search_pipeline=book_pipeline
{
  "sort": [
    {
      "rating": {
        "order": "desc"
      }
    }
  ]
}
```

**Comment by mingshl** [comment]
> I did some research and I think we might be able to leave out the sorting functionality as there exists a sort results functionality within OS core [you can see here ](https://opensearch.org/docs/latest/search-plugins/searching-data/sort/), this feature allows you to search within the search hits.
> 
> 
> 
> In essence this allows you to define a search pipeline with the rescore processor and then after you are done you could sort by the `_score` field. I feel that more discussion though.
> 
> 
> 
> Here is an example
> 
> ```
> 
> GET /my-index/_search?search_pipeline=book_pipeline
> 
> {
> 
>   "sort": [
> 
>     {
> 
>       "rating": {
> 
>         "order": "desc"
> 
>       }
> 
>     }
> 
>   ]
> 
> }
> 
> ```

Good that you found out the sort function in the query. The intention for rescore and sort is that the new score (rather than BM25 score) is added during the search response processors, then we can utilize the new score field (which not exists in the document either) then rescore processor can be helpful for ranking the hits and replace the scores.

**Comment by brianf-aws** [comment]
After discussing (offline) we have some suggestions to this processor
- Naming it rescore maybe a bit misleading we had devs thinking this was applying an algorithm in reality it was not. Here are some names they thought of `ScoreAdjustmentProcessor, ScoreModifierProcessor, ScoreUpdaterProcessor, RankOverProcessor , RefineScoreProcessor, ReorderProcessor`.
- deciding to keep only `field_to_sort_by` as a mandatory field and give the possibility for the sort order to be null this gives the flexibility for the user to apply the sorting on the search query as mentioned above.
    - Given that we are leaving this field optional we will have to think about renaming the fields as well such as `field_to_sort_by` ->`target_field`
- Add a manual check to see if `(replaceScore: False, remove_sort_field: True)` because in this scenario the user deletes a field that the result is sorted by but doesnt know why as the field is removed. When this occurs we will throw an exception, because its possible for the user to turn on `remove_sort_field` because the default is set to false

**Comment by ohltyler** [comment]
@brianf-aws  / @mingshl can this be resolved?

**Comment by brianf-aws** [comment]
Yes we can close it as this was implemented here https://github.com/opensearch-project/neural-search/pull/932
