### ISSUE TITLE
[BUG] DeprecationLogger - Unbounded memory usage

### ISSUE THREAD

**Issue by rajiv-kv** [opensearch-project/OpenSearch#16702]
### Describe the bug

DeprecationLogger dedupes messages that has been already logged based on value of `X-Opaque-Id` provided in request.
Keys set is maintained in [DeprecatedMessage](https://github.com/opensearch-project/OpenSearch/blob/b1a7743b83913ebe0c40744131c5996608e324a0/server/src/main/java/org/opensearch/common/logging/DeprecatedMessage.java#L50). The entries in set are unbounded and are appended based on the user provided header value `X-Opaque-Id`. In case the user ends up passing unique Opaque-Id per request it can result in OOM on node.

### Related component

Other

### To Reproduce

1. Create a system index in cluster say `system-test-index-1`
2. `curl -H "X-Opaque-Id: <timestamp-in-milliis>" "https://<endpoint>/_all/_alias/test-alias" `
3. Repeat step 2 for 10K times and you will notice increased heap memory usage

### Expected behavior

DeprecatdMessage#keys should be memory bounded and not result in out-of-memory.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by dblock** [comment]
@rajiv-kv Thanks for raising this, definitely an issue. Want to contribute a fix? Maybe a circuit breaker?

**Comment by rajiv-kv** [comment]
> @rajiv-kv Thanks for raising this, definitely an issue. Want to contribute a fix? Maybe a circuit breaker?

Sure @dblock - can explore.

**Comment by dblock** [comment]
This was introduced in https://github.com/opensearch-project/OpenSearch/pull/1660, @andrross we both missed this. I think the map should both have an expiration and be capped in size (in bytes) + be adjustable.

**Comment by andrross** [comment]
> I think the map should both have an expiration for its items and be capped in size (in bytes) + be adjustable.

@dblock I think a fixed-sized LRU cache with no expiration would probably be fine? If you happen to fill up the cache then you start evicting the least recently accessed items, potentially leading to duplicated log messages for those keys. I'd definitely like to avoid the complexity of making it adjustable. We probably don't need to overthink this because the goal is to de-dupe _most_ messages to avoid spamming the log.

**Comment by andrross** [comment]
Actually, I wonder if this is a good application for a bloom filter? A small amount of false positives are probably tolerable, because they just lead to duplicate log messages.

**Comment by shwetathareja** [comment]
@andrross  Yes, the first thing is that it should be bounded so that it doesn't keep on growing. But, I would like to understand the logic behind opaque-id to be appended, if all requests have unique id it doesn't help at all.

**Comment by rajiv-kv** [comment]
Is there a way for user to see the `X-Opaque-Id` in logs ? I am trying to understand if there is any downside if we track the messages at per feature (`Key`) rather than per request (`KeyWithXOpaqueId`).

**Comment by shwetathareja** [comment]
@dblock @andrross Thanks for updating the documentation and stating the usage of X-Opaque-Id header. But this may not be enough, we need to audit all the official clients like OpenSearch-hadoop to ensure it is used correctly. In case, a user gets into trouble simply because the opensearch clients are mis-using the header, that's not good experience.
