### ISSUE TITLE
Propose better integration test that exercise real cloud plugins

### ISSUE THREAD

**Issue by anasalkouz** [opensearch-project/OpenSearch#1763]
**Is your feature request related to a problem? Please describe.**
We need to enhance our integration tests to exercise the usage of real cloud plugins Like Azure, Google Cloud ..etc. This is was clearly needed after we received the repository-azure plugin issue as regression if OpenSearch 1.2 release.

1. Define account creds in Jenkins secret store. Export same in jenkins file as environment variables so that tests can consume/use them. 
2. Create different cloud providers account. 
3. Create jenkins setup locally to verify tests works. 
4. Add new account creds in Jenkins secret store for prod jenkins. 

**Additional context**
More details: #1734 #1740

**Comment by dreamer-89** [comment]
Looking into it.

**Comment by reta** [comment]
@dreamer-89 the `XxxThirdPartyTests` in the repository plugins are runnable against real cloud storages (Azure / S3 / GCS), only a matter of system properties, but there are no CI integrations + test accounts  at the moment for that.

**Comment by dreamer-89** [comment]
@reta: Thank you for sharing this.

**Comment by dreamer-89** [comment]
Checked different repository actions and corresponding integration tests already exists for all supported repository typesa. There is some plumbing work is pending; regarding feeding credentails for different cloud providers. I have verified that providing aws credentails as enviornment variables; the tests were able to use actual S3 end-point and perform different actions. The actual choice of infra to store credentials will depend on [Issue 136](https://github.com/opensearch-project/opensearch-infra/issues/136); which looks like is weighing in towards current Jenkins set up we have. I am biased towards GHA workflows for multitude of reasons already mentioned in [136](https://github.com/opensearch-project/opensearch-infra/issues/136) :)

**Comment by peterzhuamazon** [comment]
Meeting notes:
* @dreamer-89 wants to check whether we can have a system to connect to third party cloud and test.
* Seems like we need to do external communication to Azure and Google Cloud.
* A one-pager will be prepared to get some high level understanding of what is needed, and what port to open and what service to use, etc.
* Security Practices

**Comment by dreamer-89** [comment]
![Repository tests](https://user-images.githubusercontent.com/79435743/151221820-ff82cc44-9371-4b6f-8ffb-4135efc5f76a.png)


Choice of host for running test

AWS Ec2  via Jenkins

* Pros
    * Faster
    * Existing gradle check already running on Jenkins agents (EC2 host), no extra setup required other than feeding credentials
* Cons
    * May need to get AppSec approval and it involves communication with external cloud providers

Azure via Github Actions

* Pros
    * No need to go through AppSec 
    * No need to maintain infra for running the test
* Cons
    * Need to maintain a separate GHA for repository tests
    * Carve out repository tests as separate test.

**Comment by dreamer-89** [comment]
Waiting on [Issue 136](https://github.com/opensearch-project/opensearch-infra/issues/136) for choice of infra (Jenkins Vs CodeBuild Vs GHA) and review from infra team on requirements.

**Comment by dreamer-89** [comment]
Listing down pre and post test coverage with introduction of AWS pertaining to repository-s3 plugin.

### plugin/repository-s3
Today, tests use mocked servers (S3HttpHandler, Minio server) providing S3 compatible APIs for running the S3 integration tests. repository-s3 gradle uses `useFixture` var (true when permanent creds are provided) to govern whether to use mocked servers or actual S3 service.

Below are the set of tasks which runs today as part of CI gradle check.
- yamlRestTestMinio. Runs `20_repository_permanent_credentials` test using minio server.   
- yamlRestTestECS. Runs `50_repository_ecs_credentials` using  `s3-fixture-with-ecs` (S3HttpHandler mock s3 server).
- yamlRestTest. Runs `20_repository_permanent_credentials`, `30_repository_temporary_credentials`, `40_repository_ec2_credentials` using respective fixtures. 
- testRepositoryCreds. Runs RepositoryCredentialsTests
- s3ThirdPartyTest. runs S3RepositoryThirdPartyTests
- internalClusterTest. runs S3BlobStoreRepositoryTests
- test. runs all tests under test package.

When permanent credentials are provided; all tasks run except `yamlRestTestMinio` and `yamlRestTestECS`. `yamlRestTest` only runs tests in `20_repository_permanent_credentials` which is fine and probably [intentional](https://github.com/opensearch-project/OpenSearch/blob/main/plugins/repository-s3/build.gradle#L193) as tests are supposed to verify integration with AWS S3 on basic operations and not the underlying authentication. Though, running these missing test/task should be straightforward, by using a new var [here](https://github.com/opensearch-project/OpenSearch/blob/main/plugins/repository-s3/build.gradle#L104) (e.g. useFixtureECS) to govern whether to run test fixtures or use actual service end-points for temporary, ec2 and ecs cred based yaml tests.  

@reta @andrross : WDYT ?

**Comment by reta** [comment]
@dreamer-89 thanks for the summary, afaik, the most interesting tests for us are `xxxThirdPartyTest` (for S3, `s3ThirdPartyTest` but others have the analogous test suites), those exercise end-2-end flows and accept external endpoints.

**Comment by dreamer-89** [comment]
> @dreamer-89 thanks for the summary, afaik, the most interesting tests for us are `xxxThirdPartyTest` (for S3, `s3ThirdPartyTest` but others have the analogous test suites), those exercise end-2-end flows and accept external endpoints.

Thanks @reta for the reply. Yes, I verified that s3ThirdPartyTest uses actual external service end-points. Verified that tests create relevant artefacts under provided S3 bucket and base path.

**Comment by dreamer-89** [comment]
Jenkins gradle job is updated to export permanent aws account credentials. This results in s3ThirdPartyTest tests (and yamlRestTest `20_repository_permanent_credentials`) using actual s3 end-points.

**Comment by dreamer-89** [comment]
Jenkins gradle job is updated with Azure credentials. Gradle check is now running repository-azure tests using actual azure end-points.

**Comment by dreamer-89** [comment]
Closing this issue and creating new one to track GCP integration and enabling back Ec2/ECS credentials related repository-s3 integration tests discussed in previous comment [here](https://github.com/opensearch-project/OpenSearch/issues/1763#issuecomment-1119108064)
