### ISSUE TITLE
[BUG] Opensearch is not compatible with springboot 2.6.x 

### ISSUE THREAD

**Issue by oridool** [opensearch-project/OpenSearch#1926]
**Describe the bug**

Application stops working after upgrade from springboot 2.5.8 to 2.6.2.

**To Reproduce**
When running my application with springboot 2.6.2 (spring-data-elasticsearch:4.3.0, elasticsearch-rest-high-level-client:7.15.2) and opensearch 1.2.3 (current latest), all queries fail with the following exception:

```
org.elasticsearch.ElasticsearchException: Elasticsearch version 6 or more is required
	at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2084) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1732) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1702) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1672) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
	at org.elasticsearch.client.RestHighLevelClient.index(RestHighLevelClient.java:1029) ~[elasticsearch-rest-high-level-client-7.15.2.jar:7.15.2]
```

Before the upgrade, when using Springboot 2.5.X (spring-data-elasticsearch:4.2.7 with elasticsearch-rest-high-level-client:7.12), I have no issue.

**Expected behavior**

No errors when upgrading to latest springboot (spring-data-elasticsearch).
Perhaps the server can identify itself as a compatible version by configuration, to match the existing clients.

**Host/Environment (please complete the following information):**
 - OS: Centos8
 - Version OpenSearch 1.2.3

**Additional context**
I am aware of initiative of spring-data-elasticsearch to add a support for different clients:
https://github.com/spring-projects/spring-data-elasticsearch/issues/1918 
But this doesn't going to be completed soon, and until then it seems we cannot upgrade to SB 2.6.x.

**Comment by reta** [comment]
@oridool I don't think this could be solved by OpenSearch, the Elasticsearch HLRC has been hardened [1] recently to connect to Elasticsearch clusters only (basically a bunch of validations). Possible options (if it works for you) is try to downgrade `elasticsearch-rest-high-level-client` to `7.12.x` line or use older `4.2.x` release line of the Spring Data Elasticsearch, its compatibility level is the same as `4.3.x` as per official documentation [2].

[1] https://github.com/elastic/elasticsearch/pull/73910/files
[2] https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#preface.versions

**Comment by oridool** [comment]
Thanks @reta ,
I did as you suggested and for now it works. 
I just hope I won't need to use latest spring-data-elasticsearch (bugfix or new feature).

I bring here the gradle configuration I used, in case someone has the same issue:
```
buildscript {
    ext {
        set('elasticsearch.version', '7.12.1')
    }
}

dependencies {
    compileOnly (
//          downgrade to spring-data-elasticsearch:4.2.7 and avoid the OpenSearch error "Elasticsearch version 6 or more is required"
          "org.springframework.data:spring-data-elasticsearch:4.2.7",
    )
   ...
```

**Comment by kNav008** [comment]
Description:
=========
Architecture as below:
spring-boot-starter-data-elasticsearch:2.6.2
version.elasticsearch-client=7.15.2
version.Opensearch-domain=1.1


Connection failing as expected with error as below :
version : opensearch 1.1
error: nested exception is ElasticsearchException[Invalid or missing tagline [The OpenSearch Project: https://opensearch.org/]]"}

After the suggested workaround to downgrade and use version.elasticsearch-client=7.12 (as version for successful connection is 7.13.4 )https://opensearch.org/docs/latest/clients/index/, using spring-boot-starter-data-elasticsearch 2.5.0
, which has vulnerability issues.

Goal
====
Any workaround here, as any version of spring-boot-starter-data-elasticsearch client lower than 2.6.2 is giving vulnerability issues, on contrary only lower version of this client are compatible to use with OpenSearch domain( as elasticsearch-client =7.12 is supported ).

Summary of issue
=============
Connection FAILING due to unsupported version of client i.e 7.15

spring-boot-starter-data-elasticsearch:2.6.2
version.elasticsearch-client=7.15.2

Connection SUCCESSFUL but facing vulnerability due to version lower than 2.6.2 of spring-boot-starter-data-elasticsearch

spring-boot-starter-data-elasticsearch:2.5.0 
version.elasticsearch-client=7.12.0

**Comment by dblock** [comment]
I am afraid the best path forward is to fork spring-boot-starter-data-elasticsearch and client that don't have client-side version checks.

**Comment by eean** [comment]
you can't even use an older open source ElasticSearch server like 7.9 anymore because of these version checks. Supposedly it was always the case that you were not supposed to upgrade your high level elasticsearch client before upgrading your server, which is rather unrealistic for ISVs.  But now they are enforcing this guideline with these checks.

**Comment by rlanger81** [comment]
What exactly do I have to do to be able to work with an Opensearch cluster and Spring Boot 2.6.x?

**Comment by reta** [comment]
@rlanger81 if you are using Graldle, please check [this comment ](https://github.com/opensearch-project/OpenSearch/issues/1926#issuecomment-1015213344)
