### ISSUE TITLE
About hot-warm-cold architecture

### ISSUE THREAD

**Issue by LuigiCerone** [opensearch-project/OpenSearch#1990]
Hello everyone,

I’ve setup a basic how-warm-cold architecture by following the [official example](https://opensearch.org/docs/latest/im-plugin/ism/policies/#example-policy). Once the system is up and running and policy gets triggered, I’ve indexes in different states (hot/warm/cold). I was wondering, is there any way to perform a search query using the `log` alias and limit the query on a subset of backing’s indexes that are in a specific state? In other words, can I restrict the search query only on hot backing indexes associated to an alias?
For now, the only way I could achieve this was by using timestamp filter but this forces me to know the policy rules. I need to know for how long an index is in hot state so that I can use this amount as filter parameter. 

I was looking for something like [elasticsearch _tier](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-tier-field.html) in which you don’t have to know this information, you just need to specify the temperature that the indexes associated to the alias must have.

Thanks.

**Comment by reta** [comment]
Hi @LuigiCerone , there are a few issues on the subject [1], [2] but no details fleshed out just yet. The limiting search to particular tier or tiers would definitely be part of it, I think you could add this comment to [1] to keep it visible, thank you.

[1] https://github.com/opensearch-project/OpenSearch/issues/1052
[2] https://github.com/opensearch-project/OpenSearch/issues/740

**Comment by LuigiCerone** [comment]
Closing in favour of #1052, thanks :)

**Comment by peterdm** [comment]
I don't see how #1052 addresses this important question raised by @LuigiCerone .

The point of data tiers is twofold:  (1) manage the cost of perpetual data growth by trading down on hardware and latency for older data.  (2) Use data tiers effectively when querying.

If my application simply queries the alias set up by the ILM policy, I'm going against every index, no matter what tier.  That means that searchable snapshots crawl their way out of frozen, and make me twiddle my thumbs waiting to get data back even if I'm only intending to search recent data.

Digging through Release Notes (this is not really documented otherwise), there is some mention of the "can_match" prefilter step.  It looks like Frozen nodes store min/max for each numeric field in a shard-level cache so they can respond to "can_match" on behalf of their searchable snapshots without having to bring snapshots into memory.

https://www.elastic.co/guide/en/elasticsearch/reference/7.16/release-highlights.html?elektra=stack-and-cloud-7-16-blog#_search_improved_can_match_phase_for_scalability

This means that frozen shards don't get defrosted unnecessarily, which is great, but the client still needs to know the rollover policy to be able to ringfence the hot/warm date-ranges effectively. 

The `_tier field` doesn't effectively do this either, because it contains the "first preference" originally set when the index was created ... not the actual tier upon which it currently resides.

https://www.elastic.co/guide/en/elasticsearch/reference/8.0/mapping-tier-field.html

Would be nice to route queries specifically to a tier(s).  Essential for time-based applications with high query volume in fact.
