### ISSUE TITLE
Concurrent Searching: Support Early Termination

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#2586]
**Is your feature request related to a problem? Please describe.**
Early termination and time-bounded search are exception-driven and may return partial results (whatever collected up to the point of termination). When search goes over segments concurrently, it is difficult to replicate the sequential behaviour as-is (in this case the flow is interrupted and the reducers are not available, no results). 

**Describe the solution you'd like**
Find the way to propagate early termination and time-bounded search conditions in case of concurrent segments traversal, without introducing the additional synchronization.

**Describe alternatives you've considered**
The early termination and time-bounded search do not return partial results right now.

**Additional context**

**Comment by jed326** [comment]
Hey @reta what's the status of this issue? I saw you have a draft PR #4906 where it looks like you took a crack at using the Lucene IndexSearcher timeout but ultimately put it off. If you're not actively working on this do you mind if I pick it up?

**Comment by reta** [comment]
Hey @jed326 , yeah sure, please go ahead, the issue with Lucene's IndexSearcher timeout was related to very closed APIs, it was difficult to extract that from IndexSearcher  since all methods were either private or package private (and I didn't want to copy/paste)

**Comment by jed326** [comment]
Sharing some more detailed thoughts on this below

---

## Problem Overview

Currently, if the query phase fails for whatever reason, no partial results will be returned for the failed shard in the concurrent search case. If an exception is thrown during [searcher.search()](https://github.com/opensearch-project/OpenSearch/blob/068404ed1cef5e1d023816d57054aef98a7aa343/server/src/main/java/org/opensearch/search/query/ConcurrentQueryPhaseSearcher.java#L81) https://github.com/opensearch-project/OpenSearch/blob/068404ed1cef5e1d023816d57054aef98a7aa343/server/src/main/java/org/opensearch/search/query/ConcurrentQueryPhaseSearcher.java#L81 in the query phase searcher then reduce will not get called and no TopDocs will be collected.

Going a level deeper, in Lucene whenever the search thread is [blocking on the index searcher threads](https://github.com/apache/lucene/blob/branch_9_7/lucene/core/src/java/org/apache/lucene/search/IndexSearcher.java#L724-L732), if any of the threads encounter an exception then we will not add the collectors for the rest of the slice segments. This means that even if we call reduce on all the collectors from the query phase, we will still not get the full partial results from the concurrent executions.

## Lucene Timeout Implementation

This was already explored as a part of #4906 and #4487 but I took another look for my own understanding.
Looking at the latest Lucene code, I see a few issues with going down this path

* The biggest problem is that [TimeLimitingBulkScorer.TimeExceededException is package private](https://github.com/apache/lucene/blame/main/lucene/core/src/java/org/apache/lucene/search/TimeLimitingBulkScorer.java#L32). Since we are [overriding IndexSearcher.search with our own implementation](https://github.com/opensearch-project/OpenSearch/blob/8eea7b986453271cd227a7b98ee09e70d5e28634/server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java#L284-L354) https://github.com/opensearch-project/OpenSearch/blob/8eea7b986453271cd227a7b98ee09e70d5e28634/server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java#L284-L354, that makes it difficult for us to catch the correct exception in our implementation.
* The timeout is done by the TimeLimitingBulkScorer, which means that timeout is only checked in the collection phase currently. On the other hand, the OpenSearch timeout implementation is done with a [runnable that checks for timeouts](https://github.com/opensearch-project/OpenSearch/blob/90678c2d76ed1c31aebc85a23fe5be12f6e81417/server/src/main/java/org/opensearch/search/query/QueryPhase.java#L309-L329) https://github.com/opensearch-project/OpenSearch/blob/90678c2d76ed1c31aebc85a23fe5be12f6e81417/server/src/main/java/org/opensearch/search/query/QueryPhase.java#L309-L329
    * See https://github.com/apache/lucene/issues/11677 
* This also does not solve for partial results in the early termination case because a different exception is thrown for that and we need to [handle both cases](https://github.com/opensearch-project/OpenSearch/blob/90678c2d76ed1c31aebc85a23fe5be12f6e81417/server/src/main/java/org/opensearch/search/query/QueryPhase.java#L353-L370) https://github.com/opensearch-project/OpenSearch/blob/90678c2d76ed1c31aebc85a23fe5be12f6e81417/server/src/main/java/org/opensearch/search/query/QueryPhase.java#L353-L370

## Exception Handling

For now I believe the best solution is to handle the exceptions in ContextIndexSearcher and keep track of if the search has timed out. It looks like we are already doing something similar with [CollectionTerminatedException](https://github.com/opensearch-project/OpenSearch/blob/8eea7b986453271cd227a7b98ee09e70d5e28634/server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java#L332-L335) (https://github.com/opensearch-project/OpenSearch/blob/8eea7b986453271cd227a7b98ee09e70d5e28634/server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java#L332-L335).
The difficulty here is coming up with a way to propagate the the timeout without using the exception. I’ll list out the places I’ve thought of below:

* We could provide our own implementations of the [concurrent search search() methods in IndexSearcher](https://github.com/apache/lucene/blob/branch_9_7/lucene/core/src/java/org/apache/lucene/search/IndexSearcher.java#L683-L735) (https://github.com/apache/lucene/blob/branch_9_7/lucene/core/src/java/org/apache/lucene/search/IndexSearcher.java#L683-L735), however that is going to require copying a lot of code since a lot of the dependency methods are package private. It would however be very straightforward to simply catch and throw the timeout exception outside of the blocking for loop.
* In ContextIndexSearcher.searchLeaf we have access to searchContext, so we should be able to catch the exception there and set the timeout parameter. This seems pretty straightforward to me so I'm planning on following up with a PR for this implementation.
