### ISSUE TITLE
[Remote Store] Make repository name configurable

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#3286]
**Describe the solution you'd like**
As remote store depends on repository plugin to store/restore segments to/from the remote store, before creating the index with `remote_store=true`, it is required to create the repository first. As part of the change introduced in https://github.com/opensearch-project/OpenSearch/pull/3285, the repository name is hardcoded. But it takes away the flexibility and would create issues if the repository with the same name exists. The repository name should be configurable.

**Comment by satyajitg28** [comment]
Ideas and concerns around this:
1. Any hard-coded or predetermined name of the repository can conflict with an already existing repository that the customer might have.
2. For a configurable name or a name that the customer wants to choose, we might have to expose it as a non-dynamic (not update-able) cluster setting, and hence, the repository name has to be initialised in the settings file (yml) of all the nodes for it to be picked up. The problem here might be that the repository name is now confined to the scope of the node and not at a global cluster level.

Please feel free to add any other thoughts/concerns regarding this.
