### ISSUE TITLE
Do you have any plans to fix bugs in Apache 2.0 licensed Elasticsearch 7.10.2 itself?

### ISSUE THREAD

**Issue by lliu0947** [opensearch-project/OpenSearch#3365]
**Is your feature request related to a problem? Please describe.**
OpenSearch is a community-driven, open source search and analytics suite derived from Apache 2.0 licensed Elasticsearch 7.10.2 & Kibana 7.10.2。There are many bugs to be fixed in Apache 2.0 licensed Elasticsearch 7.10.2，and these bugs may have been fixed in later versions of Elasticsearch, do you plan to migrate the bug fix patch over there?

**Comment by jkowall** [comment]
Although this sounds reasonable in theory. It represents an issue because of the licensing conflicts. Open search is going to remain apache 2.0 compliant which means the code from non-Apache 2.0 licensed projects cannot not be used directly or the license will be tarnished. Therefore the code must be fixed separately. If there's a specific bug that you're running into you should file a bug report.

**Comment by dblock** [comment]
@jkowall is 100% correct

Please do not copy non-APLv2-licensed code from ES 7.10.2+, but feel free to reimplement any of the fixes independently. When making pull requests, if referencing ES, please confirm that the code is not copied from ES.
