### ISSUE TITLE
[Feature/extensions] getNamedXContent - Add support for extensions

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#3379]
Add extension framework support for getNamedXContent extension point.

**Comment by joshpalis** [comment]
Design to add support for default extension point - getNamedXContent.

**Comment by joshpalis** [comment]
Design for default extension point support for getNamedXContent.

Extension Point Purpose :
-  When plugins override getNamedXContent() with their own implementation, they are able to register custom parsers for NamedObjects within the NamedXContentRegistry. XContent Registry entries consist of a category class and object name that is mapped to a reader that provides the ability to deserialize a provided context into the corresponding object. 

Previous workflow: 
- Traditionally installed plugins override the getNamedXContentRegistry() extension point and return a collection of XContentRegistry.Entry's
- During OpenSearch bootstrap within Node.java, XContent Registries from various modules (ie: search, index, network, cluster) and all plugins are consolidated into a central XContentRegistry that is then passed as an argument to multiple services. 

Extensibility workflow: 
- Within Node.java, after all installed plugin xcontent registries are collected, extensions orchestrator will send out requests to all extensions that have been previously discovered for any entries they want to register
- Upon receiving the request, the independent plugins would return a response consisting of all the entries that it wants to register, however, instead of providing the custom parser within the entry, the reader will be replaced with a callback method to send a request from opensearch to the extension for object deserialization
- The work done to handle object deserialization will be done by the extension in order to maintain the separation of concerns between it and OpenSearch. In the case that the extension goes down, the entries corresponding to the extension must then be deregistered from the XContentRegistry
- Once all xcontent registries from the extensions have been collected, the registry will then be passed onto various services that are created during bootstrap

**Comment by minalsha** [comment]
Closing this issue as it is being tracked in the work being done on https://github.com/opensearch-project/opensearch-sdk-java/issues/208
