### ISSUE TITLE
[BUG] 400 Bad Request: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"

### ISSUE THREAD

**Issue by HugoKuo** [opensearch-project/OpenSearch#3484]
The filebeat shows this error after upgrading the OpenSearch to 2.0.0

2022-05-31T23:38:55.864Z	ERROR	[elasticsearch]	elasticsearch/client.go:224	failed to perform any bulk index operations: 400 Bad Request: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"},"status":400}

**To Reproduce**
Upgrade the OpenSearch from 1.3 to 2.0

 - OS: CentOS 7.9
 - Version : OpenSearch 2.0.0
 - Filebeat 7.10.2-1 and 7.12.1-1

Are these related? 

https://github.com/opensearch-project/OpenSearch/issues/2979#issuecomment-1105861790
https://github.com/opensearch-project/OpenSearch/issues/3131

**Comment by dreamer-89** [comment]
On closer look, `_type` field is defined with `omitEmpty` tag in [BulkMeta](https://github.com/elastic/beats/blob/7.12/libbeat/esleg/eslegclient/bulkapi.go#L55) struct, which means if _type is nil then _type should be absent in converted json bulk request. 

@HugoKuo Can you please share one beat event which is been used for ingestion to OpenSearch.

**Comment by nknize** [comment]
@dreamer-89 is right. The error is tripped from the [BulkRequestParser](https://github.com/opensearch-project/OpenSearch/blob/9ce845500c3901342d3cc000aa42d0a0afb8c38c/server/src/main/java/org/opensearch/action/bulk/BulkRequestParser.java#L225).  

The new [errorOnType](https://github.com/opensearch-project/OpenSearch/pull/2215/files#diff-267f51eb18d39f5fffd66c9bd03d4e05b07ccce914ac9d7510b5b67587c4cbcaR222) parameter was added to help alleviate these bwc errors but since we're relying on upstream Beats here it looks like this wasn't caught before release. The default for `errorOnType` was set to `true` when it was merged to main and backported to 2.0 but we never followed up to set this to false for client bwc because there is no [REST versioning](https://github.com/opensearch-project/OpenSearch/issues/3035) mechanism in OpenSearch to dynamically switch based on client request. I think a simple short term fix is to unblock this issue is to default `errorOnType` to `false` in a 2.0 patch release and follow up w/ a REST API versioning mechanism in 2.2 (or 2.1 if it can make the release date). 

Before releasing this as a 2.0.1 patch we need to check that this is the only incompatibility and there aren't more lingering that haven't yet been reported.

**Comment by msillence** [comment]
I'm still seeing this issue with 2.0.1

**Comment by msillence** [comment]
pubsubbeats now works with 2.0.1 if you set `"compatibility.override_main_response_version" : true`

**Comment by dreamer-89** [comment]
Thank you @msillence for the confirmation.  

@Wadlazky @HugoKuo : Can you please try OpenSearch `2.0.1` with `compatibility.override_main_response_version` set to true.

**Comment by dreamer-89** [comment]
A brief note on the fix deployed. 
Initially typed end-points were added back but later reverted as it was identified that integration is breaking at multiple places due to version check mismatch (more details in https://github.com/opensearch-project/OpenSearch/pull/3530). So, adding back typed end-points was not sufficient. Instead, [version override cluster setting](https://github.com/opensearch-project/OpenSearch/pull/3530) change was added back, that spoofs OpenSearch engine to `7.10.2` and temporarily fixes the issue.

**Comment by Wadlazky** [comment]
Thanks all for taking care of it. 
I tried `compatibility.override_main_response_version: true` in `opensearch.yml` and it works.
OpenSearch from 1.3.2 to 2.0.1
Filebeat 7.12.1

**Comment by HugoKuo** [comment]
confirmed it's working with 2.0.1 now.

**Comment by nanolonny** [comment]
Working for me too in 2.0.1 with compatibility.override_main_response_version set to true.  Does not work without this.  Please update documentation: https://opensearch.org/docs/latest/clients/agents-and-ingestion-tools/index/
I went through a whole lot of pain dealing with this issue before coming across this Github issue.  Updating the main documentation will surely spare others.

**Comment by dreamer-89** [comment]
Thanks @nanolonny for pointing this and apologies for delay on documentation part. Certainly updated doc will save a lot of time and effort. There is some discussion happened on [PR](https://github.com/opensearch-project/OpenSearch/pull/3530#issuecomment-1150161108)

Pinging @alicejw-aws @hdhalter for visibility.

**Comment by dreamer-89** [comment]
Documentation issue tracking this: https://github.com/opensearch-project/documentation-website/issues/741

**Comment by iqra-shafiq** [comment]
I tried compatibility.override_main_response_version: true in opensearch.yml and it works.
Opensearch 2.5.0
Filebeat 7.10.2

**Comment by ayodeji-awe** [comment]
> opensearch.yml
Was this done for a AWS managed Opensearch?

**Comment by mithlajkn** [comment]
@ayodeji-awe yes... filebeat 7.12.1
aws opensearch : 2.5.0
I tried compatibility.override_main_response_version: true and fixed the issue by 
```
curl -X PUT "http://your-opensearch-host:9200/_cluster/settings" -H "Content-Type: application/json" -d '{
  "persistent": {
    "compatibility.override_main_response_version": true
  }
}'
```  reference : https://docs.aws.amazon.com/opensearch-service/latest/developerguide/rename.html
