### ISSUE TITLE
[BUG] Index API (exists) always returns 200 response code in opensearch 2.0.1

### ISSUE THREAD

**Issue by nickytd** [opensearch-project/OpenSearch#3770]
**Describe the bug**
HEAD call always returns 200 OK instead of 404 as described in the [documentation](https://opensearch.org/docs/1.1/opensearch/rest-api/index-apis/exists/)

**To Reproduce**
Steps to reproduce the behaviour: Send an HEAD request with an arbitrary index name
curl -I <opensearch url>/xyz-* 

**Expected behavior**
404 response code when no such index exists

**Host/Environment (please complete the following information):**
 - Version [2.0.1]

**Comment by andrross** [comment]
This appears to be a bug related to the wildcard. For example, `HEAD /non-existent-index` will return a 404, but `HEAD /non-existent-index*` will return a 200.

**Comment by andrross** [comment]
Actually, this seems to mirror the behavior of the `GET` variant where `GET /non-existent-index` will return a 404 whereas `GET /non-existent-index*` will return a 200 with an empty list in the response body. Both APIs allow for specifying the [`allow_no_indices=false` parameter](https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/get-index/#url-parameters) which will result in the expected behavior.

@nickytd What do you think? Without thinking about this too much, it seems like maybe the index exists API shouldn't even offer the "allow_no_indices" parameter and the behavior should always be as if that were set to false. But on the other hand it might be good to keep the same options and behavior between the "index exists" and "get index" APIs.

**Comment by nickytd** [comment]
Thanks @andrross,
in my opinion there shall be no "assumed" parameters hidden in the implementation of an API. Predictability is far better option and keeping parity between "index exist" and "get index" is a better option to me. The caller of the API needs to properly set the parameters in accordance to the spec. So I am for the second option: keeping the same options and behaviours between "exists" and "get" and  documenting the parameters in the API spec.

**Comment by nickytd** [comment]
We can close the issue and the changes should be provided by the API maintainers. At least the docs in golang client shall reflect these details and also the examples published on opensearch.org.
