### ISSUE TITLE
[BUG] :  Gradle Build failed on Jenkins with Build Successful message

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/OpenSearch#4125]
**Describe the bug**
The gradle build action failed while raising the pull request, the logs says that Build Successful but github action is failed.

Link: https://build.ci.opensearch.org/job/gradle-check/1426/

**To Reproduce**
1. NA, as I am not sure how we can reun the build on jenkins. 
Jenkins link: Rerun this CI workflow: https://build.ci.opensearch.org/job/gradle-check/1426/

**Expected behavior**
The ./gradle check should have succeeded as build have succeeded.

**Plugins**
NA

**Screenshots**
NA

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by kartg** [comment]
It looks like the Github action failed because Jenkins marked the build as "unstable" - https://github.com/opensearch-project/OpenSearch/pull/3992#issuecomment-1204767637

A build is considered "unstable" if it was built successfully, but one or more publishers report it unstable. For example if the JUnit publisher is configured and a test fails then the build will be marked unstable. This means even if Gradle check is successful but if the corresponding JUnit reports show some errors it will report unstable.

In this case, it looks like [the Jenkins run 1426](https://build.ci.opensearch.org/job/gradle-check/1426/console) reported a few transient test failures:

```
Tests with failures:
 - org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.testResizeQueueDown
 - org.opensearch.common.util.concurrent.QueueResizableOpenSearchThreadPoolExecutorTests.classMethod
```

Closing this issue since this behavior is expected. Please feel free to reopen if you have further questions!

**Comment by navneet1v** [comment]
Can you please provide me a reason for those exceptions? Because when I re-run using the same code it succeeded. So this is strange.

**Comment by andreAbtahi96** [comment]
@navneet1v not sure if this is too late. But I suspect a potential issue that is occurring is... test cases are not synced with the updated code base. That inconsistency alone could trigger this issue. I've faced it myself. Where I update a decorator for example on a file, yet the test case was using an older decorator, that would trigger ci to fail. Not sure if that helps 😄

**Comment by navneet1v** [comment]
Closing this issue. as it is not happening now
