### ISSUE TITLE
[Segment Replication] Update ReplicationTarget and ReplicationListener failure exception type.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#4291]
Coming from #4278, [ReplicationTarget](https://github.com/opensearch-project/OpenSearch/blob/a023ad9cbabdde9c2bf1afb18b73f94357bb478a/server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java#L152) and [ReplicationListener](https://github.com/opensearch-project/OpenSearch/blob/a023ad9cbabdde9c2bf1afb18b73f94357bb478a/server/src/main/java/org/opensearch/indices/replication/common/ReplicationListener.java#L18-L17) accept OpenSearchException in their failure methods.  This should be narrowed to a replication specific exception type that is used in failures from recovery / replication.  Recovery already has a RecoveryFailedException, we can similarly create a ReplicationFailedException to use in the superclass.

**Comment by sreenath-tm** [comment]
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the fix will be like and pointing me to some resources to get started.

**Comment by dreamer-89** [comment]
@sreenath-tm: Apologies for the delay on response.
 
The suggested fix here is to create a new exception class `ReplicationFailedException` (? do you have a better name). This is essentially to reflect exceptions during replication , existing `OpenSearchException` is a base class for all OpenSearch  exception. `ReplicationFailedException` exception can then be used in [ReplicationTarget](https://github.com/opensearch-project/OpenSearch/blob/a023ad9cbabdde9c2bf1afb18b73f94357bb478a/server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java#L152) and [ReplicationListener](https://github.com/opensearch-project/OpenSearch/blob/a023ad9cbabdde9c2bf1afb18b73f94357bb478a/server/src/main/java/org/opensearch/indices/replication/common/ReplicationListener.java#L18-L17) instead of OpenSearchException.

**Comment by ayushKataria** [comment]
@dreamer-89 If no one else is working on this issue, I'll like to take it up as my first contribution to the project.

**Comment by dreamer-89** [comment]
> sreenath-tm

Thank you @ayushKataria for the interest. 
@sreenath-tm : Can you please confirm if you are working on this issue

**Comment by dreamer-89** [comment]
@sreenath-tm: Can you please confirm if you are working on this issue ? If not, @ayushKataria would like to take this forward.

**Comment by sreenath-tm** [comment]
Hi sorry for the delay in response. @ayushKataria please feel free to take it forward.
