### ISSUE TITLE
Suggesters Queries are limited to shard level metrics

### ISSUE THREAD

**Issue by kiranprakash154** [opensearch-project/OpenSearch#4529]
**Is your feature request related to a problem? Please describe.**
We limit suggesters Search Query to the shard level metrics only and not at index level.
The tf, df stats are all run against the shard level metrics and there is no aggregation done at the index level before we construct the response.

_Context_: 
The term suggesters query ([documentation](https://opensearch.org/docs/latest/opensearch/ux/#completion-suggester) - scroll down to the term suggester) by default should only return suggestions if the term is not found in the index. 

In simple words - If the user typed a term that is not found in the index, then probably it is a typo, so OpenSearch will suggest the next nearest words found in the index.

The suggesters queries are forced to QTF (Query then Fetch) even when explicitly run to DFS_TF -code link (https://github.com/opensearch-project/OpenSearch/blob/55eb86df0dc11dbfd11452fb837f89ab96b537be/server/src/main/java/org/opensearch/action/search/TransportSearchAction.java#L967-L976)

[More details](https://www.elastic.co/blog/understanding-query-then-fetch-vs-dfs-query-then-fetch) on QTF vs DFS_QTF

There is an issue filed (https://github.com/elastic/elasticsearch/issues/23838) with ES about this and I did not find an explanation why DFS_QTF is disabled. 

I could not find a relevant PR in the commit history with an appropriate description about the idea behind limiting such query to only the shard level.

**Describe the solution you'd like**
Run term suggesters the query against the index level metrics for a better UX.
If not, we need to at-least clearly document this behaviour.

**Additional context**
Reproduce the issue - 

1. Create an index with multiple shards (OS creates an index with 5 shards by default)
2. Index a document - “league”
3. Index another document - “leave”
4. [Route them](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-routing) to different shards
5. Create the most basic Suggesters query from [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html) and search for “league”
6. You will see a suggestion with “leave”

We should have returned no suggestions since the word `league` is present in the document corpus.

**Comment by macohen** [comment]
@opensearch-project/docs we should document this behavior for now. @kiranprakash154 are you interested in providing a solution for this? Happy to have a contribution even to get this moving in the right direction. I wonder if there will be a performance impact on collecting stats across shards that will make this prohibitive or at least hard to do (which could be fun) 😀

**Comment by kolchfa-aws** [comment]
@macohen Could you open an issue in the doc repo to fix this? Do I understand correctly that right before this section https://opensearch.org/docs/latest/search-plugins/searching-data/did-you-mean/#term-suggester-options we should add a note saying "Suggester queries work at the shard level and not at the index level."?

**Comment by msfroh** [comment]
I think this issue is a bit prescriptive on a specific solution. 

My understanding is that the real issue is that the term in question is found on one shard, so that shard doesn't offer a suggestion. Meanwhile the other shard doesn't have the term in question, so it offers a suggestion. The problem is that the coordinator receives these two responses and merges them before returning.

Really there are three types of responses possible:
1. Term was found (so no suggestions).
2. Term was not found, but offer suggestions (with low edit distance)
3. Term was not found, and nothing was within the edit distance threshold.

The problem right now is the option 1 is indistinguishable from option 3 (as far as I can tell). Why don't we fix that? The suggest response from each shard should differentiate between "I found the term" and "I didn't find the term and found nothing close to it". Then the coordinator could return no suggestion if any shard found the given term.
