### ISSUE TITLE
[Feature/Extensions] [BUG] SettingsModule#registerDynamicSetting contains unreachable code

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/OpenSearch#4531]
**Describe the bug**

`registerDynamicSetting()` javadocs state:
> Settings can be of Node Scope or Index Scope.

However, this is a "must". And regardless of the scope, some of this code isn't reachable:

https://github.com/opensearch-project/OpenSearch/blob/e08d57be0bd6df2243a9240931bce04f2acfdee9/server/src/main/java/org/opensearch/common/settings/SettingsModule.java#L188-L203

In the case the setting has neither Node nor Index scope, line 190 calls `registerSetting()` which contains this code:
```java
if (setting.hasNodeScope() || setting.hasIndexScope()) {
    if (setting.hasNodeScope()) {
        // ...
    }
    if (setting.hasIndexScope()) {
        // ...
    }
} else {
    throw new IllegalArgumentException("No scope found for setting [" + setting.getKey() + "]");
}
```
This jumps immediately to the catch block with an unhelpful log message.

In the case it has Node Scope it passes the first check but returns at line 192. 

In the case it has Index Scope and not Node Scope it returns at line 195.  However it never reaches this line if it has both Index Scope and Node Scope.

There is no possibility of it ever reaching the log message at line 197.

**To Reproduce**
1. Attempt to register a setting without either Node Scope or Index Scope
2. Observe the failure to register
3. Wonder why, edit the code to produce a stack trace 
4. Find the IllegalArgumentExcxeption that gets swallowed in the catch block.

**Expected behavior**
Log warnings that clearly state why it didn't work (e.g., you didn't have the correct scope).  I believe including the caught exception in the re-thrown exception would provide a "Caused By" link to clarify it, but haven't tested this.

**Comment by dbwiddis** [comment]
The code above is no longer relevant after merge to main.  #5495 rewrote the code.

However, tagging @ryanbogan as the new code doesn't seem to match the docs.   The javadoc says settings can be either node or index scoped, but they are registered regardless of the scope.  Should 'registerSetting(setting)` on line 202 be moved into the conditional?
https://github.com/opensearch-project/OpenSearch/blob/715ff72c1bf1ca31e861639faa664f92f6115501/server/src/main/java/org/opensearch/common/settings/SettingsModule.java#L185-L222

And while I'm making requests, can use `e.getMessage()`for the initial log error at line 218?  "Could not register setting plugins.anomaly_detection.ad_result_history_rollover_period" is not nearly as helpful as "Cannot register setting [plugins.anomaly_detection.ad_result_history_rollover_period] twice"

**Comment by ryanbogan** [comment]
@dbwiddis The `registerSetting()` calls for `clusterSettings` and `indexScopedSettings` return booleans representing if the settings are of node or index scope and complete part of the settings registration process.  These values are then used for logging if registration is successful, or to unregister the setting (revert the part of the registration done above) if an error occurs at any point in the rest of the settings registration.  The remaining registration occurs in the private, static `registerSetting()` method that is in the `try` block.  Within this method, an `IllegalArgumentException` is thrown if there is an error or if the setting is not node or index scoped.  This exception is then caught by the `catch` block outside the private method.  That being said, I do agree that the `SettingsException` should contain `e.getMessage()` instead of the current duplicate phrase, so that should be the action item for this issue.

**Comment by dbwiddis** [comment]
>  I do agree that the `SettingsException` should contain `e.getMessage()` instead of the current duplicate phrase, so that should be the action item for this issue.

To reduce confusion, let's close this issue and add that action item to a different issue, like https://github.com/opensearch-project/opensearch-sdk-java/issues/366 which specifically calls out the "unhelpful error message".   I linked to the above comment but we can just replace the action there.
