### ISSUE TITLE
[PROPOSAL] deprecate the changelog file

### ISSUE THREAD

**Issue by seraphjiang** [opensearch-project/OpenSearch#4769]
## What/Why
Today, there are OpenSearch repo and OpenSearch-Dashboards repo maintain both release-notes as well as change log. Although there is some benefit to clear change log history. There are also down side 1. It is a bit redundant with release note. 2. It is hard to determine which change should add to change log, in practices, developer is requested to add changelog for every PRs. Because changelog file is single file cross all branches. It leads to unnecessary **merge conflict hell** when more than 1 developer raise PR and try to merge and backport at same time.

Both repos mentioned, the changelog was inspired by [ keep a changelog](https://keepachangelog.com/en/1.0.0/) However, I was not able to find what are other top open source project adopt it and how it be adopted.

We should review and explore what's the real benefit we gain from changelog, be open to explore other large open source project to see if what's the best practices.

### What are you proposing?
1. OpenSearch developer and OpenSearch Dashboards review the benefits and pain points of changelog
2. Research other large open source projects' best practices e.g. https://github.com/torvalds/linux, https://github.com/apache/lucene
3. consider deprecate changelog or find better way to resolve  **merge conflict hell**

**Comment by dblock** [comment]
CHANGELOG was proposed and added in https://github.com/opensearch-project/OpenSearch/issues/1868, I'll add a comment about this there.

**Comment by dblock** [comment]
The two downsides mentioned are 1) merge hell, and 2) big projects don't do this. The first is a good argument and I believe @kotwanikunal has been trying to resolve it with automation, and that's one of the reasons why #1868 remains open. On the second argument, please research how other projects do it and make concrete proposals. 

Authoring release notes before release has been a much bigger pain than merge hell, and those notes typically contain a ton of poorly written or incorrect changes (see #1886), so I am personally not inclined to reverse course on introducing CHANGELOG.

**Comment by dblock** [comment]
For consolidation purposes I am going to close this. Please put your comments in https://github.com/opensearch-project/OpenSearch/issues/4769 that is still open and the jury is out of what the "final state" should be.

**Comment by seraphjiang** [comment]
> For consolidation purposes I am going to close this. Please put your comments in #1868 that is still open and the jury is out of what the "final state" should be.

my proposal is not deprecate changelog in opensearch repo, but deprecate in all repo. i think we should keep this in meta repo to discuss. not moving to specific project discussion and close it.

**Comment by kavilla** [comment]
> my proposal is not only deprecating changelog in opensearch repo, but deprecate in all repo. i think we should keep this in meta repo to discuss. not moving to specific project discussion and close it.

I think originally when the solution was looked in relied on PRs having correct labelling. But I feel more confident within the project that we utilize labelling that perhaps we can rely on this solution?

But reading the thread as well (sorry I missed it) the ideal state is that a changelog isnt a 1-to-1 to the commit history. Like if a feature came out in 2.x then I don't find much value on changelogs about any fast follows if it was unreleased before. I think part of the problems associated with a changelog and required per a commit is that it doesnt work well with feature development when multiple contributors are working on the same feature in a short amount of time. So perhaps it is a good thing that this conflict occurs because it forces developers to rebase and verify when the code is changing so frequently.
