### ISSUE TITLE
[Searchable Snapshot] Capture initial CPU profiling information

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#5217]
Performance is known to be poor (see #4797) until we implement caching and other optimizations. The task here is to capture an initial profile of the query performance, and document the steps for doing so, with the goal that we'll be able to re-run the profile to measure and validate improvements as we implement the optimizations.

**Comment by tlfeng** [comment]
Set up a local OpenSearch 2.4 node manually, with Searchable Snapshot feature enabled, installed the "repository-s3" plugin. Then had a run of the modified "[nyc_taxis](https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/1f85d5c56f586e1dcc787d8093055ba69f79451c/nyc_taxis)" workload with steps for testing Searchable Snapshot, to make my OpenSearch node has got index data and snapshot.

I initiated a flight recording using Java Mission Control (https://adoptium.net/jmc/), the recording time is 8 minutes (because the "range" query I'm going to run takes 6 minutes in my environment), and event setting is "Profiling - on server", instead of "Continuous - on server".

After started the recording, I ran the command (mentioned in https://github.com/opensearch-project/OpenSearch/issues/5172#issuecomment-1309663846) to run a range query that used in "nyc_taxis" [workload](https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/ae11cf74873bff91c7299257f1fbcb3cdde47987/nyc_taxis/operations/default.json#L37-L50):
```
$ curl -XGET http://localhost:9200/nyc_taxis/_search\?pretty --header 'Content-Type: application/json' -d '{
"query": {        
          "range": {
            "total_amount": {
              "gte": 5,          
              "lt": 15            
            }                     
          }                         
        }            
}'   
```

This is the recording result:
[flight_recording_110141orgopensearchbootstrapOpenSearch63515 range query.jfr.zip](https://github.com/opensearch-project/OpenSearch/files/10024497/flight_recording_110141orgopensearchbootstrapOpenSearch63515.range.query.jfr.zip)

**Comment by andrross** [comment]
As expected the profile is dominated by `S3BlobContainer.readBlob`. There are other issues here as well but probably not worth diving into until we have implemented caching to reduce the need to re-fetch data from the remote repository.

<img width="1024" alt="Screen Shot 2022-11-17 at 3 44 05 PM" src="https://user-images.githubusercontent.com/9160839/202584516-ea887f42-2ddd-445b-896a-78b0d897046f.png">

**Comment by tlfeng** [comment]
Close the issue, because an initial CPU profiling info has been captured and the step to get the result has been written down.
