### ISSUE TITLE
Snakeyaml vulnerability in OpenSearch 2.2.1

### ISSUE THREAD

**Issue by martin-gaievski** [opensearch-project/OpenSearch#5614]
Opensearch 2.2.1 has a dependency on vulnerable Snakeyaml version 1.26.

Dependency Hierarchy:

-> opensearch-2.2.1-SNAPSHOT.jar (Root Library)

   -> opensearch-x-content-2.2.1-SNAPSHOT.jar

     -> ❌ snakeyaml-1.26.jar (Vulnerable Library) 

Please check details of the WhiteSource scan [here](https://github.com/opensearch-project/k-NN/pull/689/checks?check_run_id=10239675835)

This is a CI blocker in case changes are required in plugin bundled with core 2.2.x.

**Comment by tlfeng** [comment]
I think OpenSearch core is not affected by the [CVE-2022-1471](https://www.mend.io/vulnerability-database/CVE-2022-1471).

Although snakeyaml library exists in the build artifact of OpenSearch, it's not used directly used by OpenSearch.
The dependency snakeyaml is used by [jackson-dataformat-yaml](https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml/2.14.1) in [opensearch-x-content library](https://github.com/opensearch-project/OpenSearch/tree/2.4.1/libs/x-content).
I checked the code repository of jackson-dataformat-yaml, snakeyaml is used for low-level YAML parsing, see [here](https://github.com/FasterXML/jackson-dataformats-text/tree/jackson-dataformats-text-2.14.1/yaml) for the code, and the vulnerble SnakeYaml's Constructor() class doesn't occur in the code base.

Currently seems it's not possible to mute the alert from security scanners, because seeing from the CVE description, the mitigation is to use alternative API, instead of upgrading the version.

In addition, [Security Analytics plugin](https://github.com/opensearch-project/security-analytics) may be affected by the vulnerability, which is not part of this code repository, and the fix will go in 2.5.0 release on Jan 17, 2023, see the PR https://github.com/opensearch-project/OpenSearch/issues/5576 for detail.

I will close the issue, please free to reopen if you have further questions.

**Comment by tlfeng** [comment]
Update on April 2023:
There are 2 locations OpenSearch use `snakeyaml`:
1. Transitive dependency for [jackson-dataformat-yaml](https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml/2.14.1) library
As confirmed from the active contributors of `jackson-dataformats-text` in the related issues (https://github.com/FasterXML/jackson-dataformats-text/issues?q=is%3Aissue+snakeyaml+cve), `jackson-dataformats` library is not affected by [CVE-2022-1471](https://www.mend.io/vulnerability-database/CVE-2022-1471).
The version of `snakeyaml` library will be upgraded in the next version [release](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15#yaml-format-module) of `jackson-dataformats-text` .
2. In class [ExtensionManager](https://github.com/opensearch-project/OpenSearch/blob/2.6.0/server/src/main/java/org/opensearch/extensions/ExtensionsManager.java)
`snakeyaml` usage is introduced in the commit https://github.com/opensearch-project/OpenSearch/commit/c2307fb82005fdd61b9d89bf35e9916ea412155d in January 2023, in OpenSearch 2.5.0. The usage is likely been affected by the CVE. 
While in OpenSearch 2.6.0, the venerability has been remediated by the commit https://github.com/opensearch-project/OpenSearch/commit/a5dc22a174e4d2964fb4e6bc84f0b27957d0fddf.
The version of `snakeyaml` has been upgraded to 2.0 in the commit https://github.com/opensearch-project/OpenSearch/commit/8bda365902ae665bc2082d5b6932b28a1fcb4803, which will be released in OpenSearch 2.7.0 and 3.0. `snakeyaml` version 2.0 is not affected by the CVE.
