### ISSUE TITLE
[Feature/Identity] Permissions API

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/OpenSearch#6127]
Use case:

There are APIs that a subject can call to create, check, and delete the permissions grants it has.

Acceptance Criteria:

  - Permissions APIs allow for curl commands to grant permissions 
  - Invalid formatted API calls are rejected
  - Permissions grants add a permission to the permission store while deletes remove a permission 
  - Permission checks return all the permissions associated with a subject

**Comment by scrawfor99** [comment]
This is being worked on in a draft [PR](https://github.com/opensearch-project/OpenSearch/pull/6117). The design follows a similar style of code implementation as the #5990. The actual calls syntax is not yet finalized but right now, I am thinking something along the lines of: 

Create Permission: 
REQUEST: `POST /permissions `
DATA: `{ permissionString: "<permissionHere", principal: "<principalHere>"} `
RESPONSE: `{msg: "create permission <permissionString> for <principal>", success: <true/false>}

Check Permission: 
REQUEST: `GET /permissions `
DATA: `{principal: "<principalHere>"} `
RESPONSE:  `[<PermissionList>]`

REQUEST: `DELETE /permissions `
DATA: `{ permissionString: "<permissionHere", principal: "<principalHere>"} `
RESPONSE:  `{msg: "create permission <permissionString> for <principal>", success: <true/false>}

**Comment by cwperks** [comment]
@scrawfor99 What do you think about listing out a few different scenarios and how the API is expected to behave in each scenario? When designing an API I generally like to start with the API contract (think OpenAPI Specification) that can clearly show the API params and expected response types. See https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v2.0/yaml/petstore.yaml and https://petstore.swagger.io/ as the quintessential examples of the use of the OpenAPI specification. The extensions SDK also has a examples you can look at: https://github.com/opensearch-project/opensearch-sdk-java/tree/main/src/main/java/org/opensearch/sdk/sample/helloworld/spec.

For this I'm not asking for a spec for this API in the openAPI format, rather describing a few different scenarios that can be translated into test cases. Off the cuff, here's a couple that come to mind:

**1. Grant Permissions API**

1. Grant a cluster permission - success
2. Grant an index permission (index pattern required) - success
3. Grant a plugin permission - success
4. Try granting an action that doesn't exist - failure // In this case what is the response code and message? Perhaps: { "success": false, "message": "action not found" }
   - Related to this, what is the general response in OpenSearch when a resource is not found. i.e. querying an index that does not exist. Should this API follow a similar convention?
5. Grant a permission that's previously been granted - Should this just respond with ok or something different?
6. Similar to 5, but with an index permission - What happens when there are 2 subsequent calls to the grant API on an index permission with different patterns. i.e. call1 - `indices:data/read/search?index-pattern=my-index*`, call2 - `indices:data/read/search?index-pattern=other-index*`
7. Since this is related to granting permissions - who has permissions to grant permissions and how are they assigned the privilege to grant permissions?
   - Since a username is required to grant permissions (the subject being granted permissions) - what do you think about having this as a route parameter to the API or do you think it should go in the body as you mentioned in the comment above?
8. Calling grant API on a user that doesn't exist

-----

On the controller side of things can you describe the data-structure that holds the permissions and what happens on a successful permissions grant?

What do you think about splitting this PR into a PR for each API: Grant, Check, Revoke?

**Comment by scrawfor99** [comment]
> @scrawfor99 What do you think about listing out a few different scenarios and how the API is expected to behave in each scenario? When designing an API I generally like to start with the API contract (think OpenAPI Specification) that can clearly show the API params and expected response types. See https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v2.0/yaml/petstore.yaml and https://petstore.swagger.io/ as the quintessential examples of the use of the OpenAPI specification. The extensions SDK also has a examples you can look at: https://github.com/opensearch-project/opensearch-sdk-java/tree/main/src/main/java/org/opensearch/sdk/sample/helloworld/spec.
> 
> For this I'm not asking for a spec for this API in the openAPI format, rather describing a few different scenarios that can be translated into test cases. Off the cuff, here's a couple that come to mind:
> 
> **1. Grant Permissions API**
> 
>     1. Grant a cluster permission - success
> 
>     2. Grant an index permission (index pattern required) - success
> 
>     3. Grant a plugin permission - success
> 
>     4. Try granting an action that doesn't exist - failure // In this case what is the response code and message? Perhaps: { "success": false, "message": "action not found" }
>        
>        * Related to this, what is the general response in OpenSearch when a resource is not found. i.e. querying an index that does not exist. Should this API follow a similar convention?
> 
>     5. Grant a permission that's previously been granted - Should this just respond with ok or something different?
> 
>     6. Similar to 5, but with an index permission - What happens when there are 2 subsequent calls to the grant API on an index permission with different patterns. i.e. call1 - `indices:data/read/search?index-pattern=my-index*`, call2 - `indices:data/read/search?index-pattern=other-index*`
> 
>     7. Since this is related to granting permissions - who has permissions to grant permissions and how are they assigned the privilege to grant permissions?
>        
>        * Since a username is required to grant permissions (the subject being granted permissions) - what do you think about having this as a route parameter to the API or do you think it should go in the body as you mentioned in the comment above?
> 
>     8. Calling grant API on a user that doesn't exist
> 
> 
> On the controller side of things can you describe the data-structure that holds the permissions and what happens on a successful permissions grant?
> 
> What do you think about splitting this PR into a PR for each API: Grant, Check, Revoke?

Hi @cwperks, thank you for your comments and suggestions. I can write a README to accompany the PR following the template you linked. I did not realize that we were supposed to follow any particular specification and was just replicating previous API implementations in OpenSearch. I will fix that though. I also will do my best to answers to your questions below. 

1. You should use `POST /permissions data: {"principalString": "<principal>", "permissionString" : "<permission to add>"}` and you will get a response of `{msg: "create permissions <permissionString> for <principal> , success: true}` 
2. Same things since the index pattern is part of the permission string. 
3. To my knowledge, we have no current implementation of plugins as subjects so this is not something that is being covered in this PR. 
4. You would not get a failure message for this since currently the permission grant functionality does not check if an action does not exist. It checks if an action type is incorrect or the permission is improperly formatted but since we would have to look at all the different actions every time you wanted to grant a permission if we were to check for matches, we only check for matches on resolution. Perhaps this is something that should be changed... 
5. Right now the plan is to allow duplicate permissions. This is a straightforward way of handling batch grants later. 
6. These are two different permissions, so you would be granted the ability to search on `my-index*` and `other-index*`. Maybe I am not answering your question though. 
7. Permissions should either only be grant-able by admins or by those with the permission already and permission granting privileges. This is not something that is implemented in OpenSearch however so that will have to be followed-up-on. Currently, I was planning on the principal going in the body for simpler handling. I had not thought about having it be a route parameter but I don't know whether there is an advantage in making that change. If you feel there is then I can swap things around. My understanding is that with REST we want to have the path parameters match only the resources which we are able to modify using the API. If we moved the principal into the route then I think we should redefine things a bit since it would mean that we were now creating a API one level closer to the client and stating that the API calls were modifying the permissions resource associated with that principal as opposed to the permissions resource associated with that cluster. 
8. There is no handling for granting a permission to a nonexistent principal. I am not sure we want a message here since it would let you brute force valid principals. Right now, a nonexistant principal granted a permission would get the permission saved like anyone else. It would just never be used since it does not exist. We could add an automatic trashing mechanism for nonexistant principals and action grants in a follow-up PR but I don't know that it impacts the basic API design. 

Let me know what you think about everything. I will do my best to swap whatever you think needs tweaking. I can also split the PR into three parts though it will be structured like Delete PR⊂ Check PR⊂ Add PR since they build on each other for integration tests.

**Comment by scrawfor99** [comment]
This is resolved with #6154 and #6220. I plan to close this when they are merged.
