### ISSUE TITLE
[BUG]Serilog not sinking logs to Opensearch

### ISSUE THREAD

**Issue by VartikaSharma14** [opensearch-project/OpenSearch#6172]
Hello
I have installed Opensearch and opensearch dashboad 2.5.0 version from docker compose file.
Attached screenshot of code how I am sinking to elasticsearch. 
<img width="644" alt="image" src="https://user-images.githubusercontent.com/99406269/216628737-3b8d39b4-8a7d-4387-a664-1757533d6276.png">

But when I check in opensearch dashboard -> No indices is created 
<img width="619" alt="image" src="https://user-images.githubusercontent.com/99406269/216629147-d83d0d8a-2850-45b3-8ded-2a0eda35510c.png">

Also getting exception on console from serilog
<img width="944" alt="image" src="https://user-images.githubusercontent.com/99406269/216629242-47de2aae-239f-4964-92b4-c863f2c4117b.png">

As I am new to opensearch. 
kindly assist me I feel a little stuck.

Thank you 
Vartika Sharma

**Comment by minalsha** [comment]
@seanneumann  can you help?

**Comment by minalsha** [comment]
Issue moved to [opensearch-project/OpenSearch-Dashboards #3379](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3379) via [**Zenhub**](https://www.zenhub.com/)

**Comment by seanneumann** [comment]
We'll take a look!

**Comment by kavilla** [comment]
As @joshuarrrr stated here: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3379#issuecomment-1419921301

There is currently no data with the cluster of that index because the bulk insert is failing to insert data. The index pattern creation page won't be able to show anything if there is no index with that name.

The reason why the bulk insert is failing is because `_type` was removed as a breaking change: https://github.com/opensearch-project/OpenSearch/pull/2239. User should update their upstream to remove that parameter and they should be able to ingest logs and therefore create an index pattern.

**Comment by dbwiddis** [comment]
> The reason why the bulk insert is failing is because `_type` was removed as a breaking change: #2239. User should update their upstream to remove that parameter and they should be able to ingest logs and therefore create an index pattern.

@VartikaSharma14 can you see if this resolves your issue?

**Comment by kartg** [comment]
@VartikaSharma14 i'll go ahead and close this out. Please feel free to reopen if the issue persists and we can assist.
