### ISSUE TITLE
[Segment Replication] Allocation changes to distribute primaries - Benchmark & document improvements using opensearch-benchmark.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#6210]
https://github.com/opensearch-project/OpenSearch/pull/6017 Introduced a new weight factor to attempt to evenly distribute primary shards.  We need to document this change including benchmarks to 1) find a reasonable default for SR enabled indices and 2) prove when using the setting is beneficial.

Related https://github.com/opensearch-project/documentation-website/issues/2663

**Comment by dreamer-89** [comment]
Looking into this.

**Comment by dreamer-89** [comment]
Copied @shwetathareja's [comment](https://github.com/opensearch-project/OpenSearch/pull/6325#discussion_r1108264474) from PR https://github.com/opensearch-project/OpenSearch/pull/6325

>My initial thoughts:

Have you looked into adding an AllocationConstraint similar to [isIndexShardsPerNodeBreached](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationConstraints.java#L79) which essentially adds constraint to ensure each node shouldn't have more than avg. no.of shards per index even if a node has overall less shards compared to other nodes. This helps in preventing un-necessary rebalances later. More details are here - https://github.com/opensearch-project/OpenSearch/issues/487

I feel you can simply add a constraint for segrep indices to ensure a node shouldn't have more than avg. no. of expected primaries for an index. Lets say it is 5 node cluster and segrep index has 5 primaries + 2 replicas. So no node should have more than 1 primary. This wouldn't require coming up with magic value for weight factor. Later, we can evaluate if we want to extend this to balancing sum of primaries across all indices across all nodes as well. e.g. 1 segrep index has 3 primaries while other has 2 primaries and it is 5 node cluster, then each node shouldn't have more than 1 primary across indices as well.

**Comment by dreamer-89** [comment]
> @shwetathareja's [comment](https://github.com/opensearch-project/OpenSearch/pull/6325#discussion_r1108264474) from PR #6325
> 

> > My initial thoughts:
> 
> Have you looked into adding an AllocationConstraint similar to [isIndexShardsPerNodeBreached](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationConstraints.java#L79) which essentially adds constraint to ensure each node shouldn't have more than avg. no.of shards per index even if a node has overall less shards compared to other nodes. This helps in preventing un-necessary rebalances later. More details are here - #487
> 
> I feel you can simply add a constraint for segrep indices to ensure a node shouldn't have more than avg. no. of expected primaries for an index. Lets say it is 5 node cluster and segrep index has 5 primaries + 2 replicas. So no node should have more than 1 primary. This wouldn't require coming up with magic value for weight factor. Later, we can evaluate if we want to extend this to balancing sum of primaries across all indices across all nodes as well. e.g. 1 segrep index has 3 primaries while other has 2 primaries and it is 5 node cluster, then each node shouldn't have more than 1 primary across indices as well.

Yes, I think having a constraint (here, avg primary shard count/node) supplements the existing weight function and provides more flexibility and get rid of primary balancing factor. Also, it will be more useful in solving uneven primary shard distribution from failover and the balancing logic which works at index level. 

>Later, we can evaluate if we want to extend this to balancing sum of primaries across all indices across all nodes as well. e.g. 1 segrep index has 3 primaries while other has 2 primaries and it is 5 node cluster, then each node shouldn't have more than 1 primary across indices as well.

Can you please share more details around this from balancing perspective ?

The [existing balancer](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java#L181) performs balancing withing single index i.e. it balance shards of one index across all nodes, repeat for others. We can introduce a new balancing logic which works across all indices and across all nodes. A simple algorithm can be:

#### Constants
Allocation constraint weight when node contains more than avg primary shards, lets say `Wa = 1000`
Threshold, say `t = 2 * Wa`. When node weight differ more than threshold, it is considered unbalanced. We use twice of `Wa` to avoid repeatitive shard movements.
#### Steps
1. Calculate weight on all nodes using weight with constraint above. `E.g. 2 nodes, say N1, N2 and 5 shards. N1 contains 2 shard, N2 contains 3. With avg shard count/ node as 2.5, N1 will have 0 weight while N2 have 1000`. 
2. Sort nodes based on constraint weight.
3. while(true)
      - Pick light node and heavy node
      - If weight diff > t, move *random* primary from heavy -> light node
         - update weight of both nodes
         - sort and continue // repeat to attain more balance
      - else break // no more unbalanced

With above algo, we can use below approaches for solving the primary shard allocation.

### Approach 1.
Have additional round of balancing based on avg primary shard/node constraint. First balance on individual indices ([existing](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java#LL181C9-L181C25)) and then balance across all nodes. 
Pros.
1. Have better per index shard distribution 
Cons. 
1. Additional relocations from second round.
2. Problems such as
     - Both round negating effect of other.
        - Example, there are 2 Nodes, say N1, N2, 3 indices (I1, I2, I3) with total 4 primary shards. 
        - I1 has 2 primary I1P1, I1P2; while I2, I3 have one primary I2P1, I3P1 respectively
        - N1 -> I1P1, I1P2 while N2 contains I2P1, I3P1. 
        - Index level balancing moves I1P1 from N1 to N2. Node level balancing moves it back
     - Endless loop of balancing actions.

### Approach 2. 
Balancer performs balancing across all indices and nodes once using algorithm above for segrep specific shards. 

Pros. 
1. Minimal shard relocations.

Cons.
1. Chances of skewed per index shard distribution that cause hot spot.

Based on above, approach 1 seems better as approach 2 can have problem of hot spots.

**Comment by shwetathareja** [comment]
Thanks @dreamer-89 for exploring the AllocationConstraint approach.

Couple of comments on different approaches
**Approach 1**
1. While calculating extra weight, the current logic can result in -ve weight as well
`int extraPrimaryCount = (int)(node.numPrimaryShards(index) - balancer.avgPrimaryShardsPerNode(index));`
  Instead you can choose to not add extra weight unless the constraint is breached.
2. Why do you think there will be extra re-balances. This will ensure primaries are balanced across shards even though the over all shard count is lower on that node compared to others.
3. Yes agreed, we will need to define different constraint (or same constraint handling both conditions) for balancing overall primaries across all indices if desired which you have discussed in Approach 2 & 3.
4. Yes, you are right, if i remember right re-balancing was not taking care of constraint. We can evolve the Allocation algorithm for re-balances as well. I will check that part of the code again.

**Approach 2**
As you mentioned, it is only balancing across all indices and wont be effective per index and that would be important from log analytics customer perspective where only the latest index will be taking writes after rollover.

**Approach 3**
For segrep, I feel this would certainly add value considering resource usage across primary and replica is very skewed. I think we need to re-look at the rebalancing algo to tune the constraint calculation logic and prevent un-necessary movements.

Overall, I am aligned to start with per index primaries to be evenly distributed and iterate over to make it evenly distribute across indices primaries as well later.

**Comment by dreamer-89** [comment]
Thank you so much @shwetathareja for the feedback!  As you mentioned, the actual implementation uses constraints based weight calculation. PR #6422 (request you to review as well). 

> Approach 1
> 1. While calculating extra weight, the current logic can result in -ve weight as well
> int extraPrimaryCount = (int)(node.numPrimaryShards(index) - balancer.avgPrimaryShardsPerNode(index));
> Instead you can choose to not add extra weight unless the constraint is breached.
> 3. Why do you think there will be extra re-balances. This will ensure primaries are balanced across shards even though the over all shard count is lower on that node compared to others.
> 4. Yes agreed, we will need to define different constraint (or same constraint handling both conditions) for balancing overall primaries across all indices if desired which you have discussed in Approach 2 & 3.
> 5. Yes, you are right, if i remember right re-balancing was not taking care of constraint. We can evolve the Allocation algorithm for re-balances as well. I will check that part of the code again.


1. The `extraPrimaryCount` calculation is guarded by `if` condition so it should not result in negative weight contribution. This logic was just for POC to verify if it works.
```
if(node.numPrimaryShards(index) - balancer.avgPrimaryShardsPerNode(index) > 0)
```
2. An extra relocation is needed to attain primary balance. This is done by first offloading extra primary on heavier node due to breached avg. primary shard count per node constraint; which may result in target node to have extra shard count and violating the threshold based of shard counts; needing another relocation (probably a replica shard). 
During rebalancing, the primaries are relocated first ([link - from PR above](https://github.com/opensearch-project/OpenSearch/pull/6422/files#diff-86f7e121124c277391014bd8372830a2860e614a7bc25318b7e42479cd0890cdR1016)) from heavier to light node. This is needed to converge delta b/w heavy & light node and to prevent never ending shard relocations. Once primary is moved, it may result shard count imbalance (weight diff higher than threshold default `1.0f`) which results in one more shard relocation. Consider this with example below, there are 3 nodes with one index (3 shards, 1 replica).
State 1

| Node 1  | Node 2 | Node 3 |
| ------------- | ------------- | ------------- | 
| P1  | P2  | P3 | 
| R3  | R1 |  R2 |

Node 3 is restarted, coordinator promotes R3 as primary resulting in below state. Node 3 joins back cluster containing R3, R2

State 2

| Node 1  | Node 2 | Node 3
| ------------- | ------------- | ------------- | 
| P1 | P2  | R3 |
| P3  | R1 | R2 |

Node 1 breaches average primary shard count per node constraint `2 primary shards > 1 allowed average primary shards`, thus rebalancer moves `P1` from `Node 1` -> `Node 3` (and not Node 2 because 1) Not allowed due to ([primary count diff](https://github.com/opensearch-project/OpenSearch/pull/6422/files#diff-86f7e121124c277391014bd8372830a2860e614a7bc25318b7e42479cd0890cdR1016) 2) SameShardAllocator allocation decider filter). This results in below state

State 3

| Node 1  | Node 2 | Node 3
| ------------- | ------------- | ------------- | 
| | P2  | R3 |
| P3  | R1 | R2 |
|  | | P1 |

Node 3 now have more number of shards which still breaches `1.0f` default [threshold](https://github.com/dreamer-89/OpenSearch/blob/primary_allocation_with_constraint/server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java#L374). Rebalancer moves `R2` back to Node 1 resulting in eventual balance. If fine tune balance is not desired, a higher threshold can be set which stops at step 3 above.

State 4

| Node 1  | Node 2 | Node 3 |
| ------------- | ------------- | ------------- | 
| P3  | P2  | P1 | 
| R2  | R1 |  R3 |


4. Yes, let's continue disucussion here (and on PR) and come up use cases where global balancing is necessary.  
5. Yes, rebalancing doesn't use any constraint today. With PR, I added the average primary shard count based constraint to be used during allocation and rebalancing. 


>Approach 2
As you mentioned, it is only balancing across all indices and wont be effective per index and that would be important from log analytics customer perspective where only the latest index will be taking writes after rollover.

👍 


>Approach 3
For segrep, I feel this would certainly add value considering resource usage across primary and replica is very skewed. I think we need to re-look at the rebalancing algo to tune the constraint calculation logic and prevent un-necessary movements.

Let's continue discussion here on use cases, which warrants global level balancing.

>Overall, I am aligned to start with per index primaries to be evenly distributed and later iterate over to make it evenly distribute across indices primaries as well.

Thank you! Yes, per index primary balancing is implemented in https://github.com/opensearch-project/OpenSearch/pull/6422; we can implement global balancing based on discussion here.

**Comment by vigyasharma** [comment]
Great discussion here, @dreamer-89 and @shwetathareja. This is a tricky, but important problem to solve. Happy to see the original [Constraint Based Shard Allocation idea](https://github.com/elastic/elasticsearch/issues/43350) continue to find utility over the years!

I think we are on the right track here. I like the option of adding two constraints, one for "primaries per index per node", and another one for "total primary shards per node". 
...

> Existing constraints are predicates which return yes/no based on whether node has breached constraint or not. It would be better if constraint returns a degree by which a constraint is breached

I would strongly suggest thinking hard about how to keep the shard weight algorithm **as simple as possible**. It is tempting to add more capabilities, but it quickly becomes exponentially complex to reason and debug shard allocation in a production cluster. This was why, in the original impl., I had made each constraint add a [fixed high value](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationConstraints.java#L22) weight, and [modeled constraints as boolean predicates](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationConstraints.java#L57-L62).

As we add multiple constraints, there are no clear answers to whether breach of a particular constraint, is worse than the breach of a different constraint. (e.g. is it worse to breach the `primariesPerIndexPerNode` constraint, or `totalPrimariesPerNode` constraint?) 
If only a single primary had recoveries, the former can be bad. If multiple primaries have recoveries, and target shard for 2 different indexes is on the same target node, the latter can be worse.
The point is, both are bad, and engineering around which is worse adds complexity with diminishing returns.

...

> Consider this with an example, with avg primary shards count per node as 2 and two contender nodes (N1, N2) where N1 contains 3 primary shards (breach threshold by 1) while N2 contains 5 primary shards (breach threshold by 3), here N2 should not be preferred.

Constraint framework today is simple - it adds `numConstraintsBreached * CONSTRAINT_WEIGHT` to the weight returned by default weight function. In the example above, N2 will already have a high value from default weight function. So even with the same `CONSTRAINT_WEIGHT` values, it will not be preferred.

That is the central idea. Let a simple default weight function do its work. Then all *eligible* nodes with no constraints breached are better than ones with 1 constraint breached, who are better than nodes with 2 constraints breached and so on.. 
This works in tandem with the "Allocation Decider" Framework; which already rules out nodes which should not even be considered for allocation or rebalance. Deciders filter out ineligible nodes. Constraints deprioritize less preferred nodes.


Finally, I think it makes sense to extend the framework to handle rebalances. I did play around with it at the time, but threw it away, since `allocation` was the only problem we were solving then. Looks like now is a good time to add it.
If you add constraint handling to rebalances, would it take care of the extra rebalances you pointed out @dreamer-89 ?

**Comment by vigyasharma** [comment]
Re: imbalances that emerge from replica -> primary promotions.. I think you need the pri-rep swap capability to truly be able to solve it. There is no other way (I know of), to solve that problem for a 2 node cluster.

**Comment by dreamer-89** [comment]
Thank you @vigyasharma for the feedback. 

> >Consider this with an example, with avg primary shards count per node as 2 and two contender nodes (N1, N2) where N1 contains 3 primary shards (breach threshold by 1) while N2 contains 5 primary shards (breach threshold by 3), here N2 should not be preferred.
> 
> Constraint framework today is simple - it adds numConstraintsBreached * CONSTRAINT_WEIGHT to the weight returned by default weight function. In the example above, N2 will already have a high value from default weight function. So even with the same CONSTRAINT_WEIGHT values, it will not be preferred.

Sorry, I was not clear enough in the example. I meant to have a state where N1, N2 have unequal primary shard count but still balanced on weight calculation. Updated the example and copy pasting below as well. I agree, let's keep the constraint as predicate and not change until it is really needed.

> 2. Existing constraints are predicates which return `yes/no` based on whether node has breached constraint or not. It would be better if constraint returns a degree by which a constraint was breached. The quantity can then be incorporated into node's weight calculation. Consider this with example of 4 node (N1, N2, N3, N4) and 1 index (8 shard, 1 replica) with 2 as `C1` value. Nodes N3, N4 are excluded from allocation. Node N1 contains 3 primary 5 replica (breach primary threshold by 1) while Node N2 contains 5 primary 3 replica (breach threshold by 3). Here, as both nodes have unequal primary and breaching `C1` and also they are balanced (equal weight because all shards belong to same index and both nodes have same number of shards). For shard allocation (increase replica count) and rebalancing, both nodes can be picked as target while it is prefera
 
> That is the central idea. Let a simple default weight function do its work. Then all eligible nodes with no constraints breached are better than ones with 1 constraint breached, who are better than nodes with 2 constraints breached and so on..
> This works in tandem with the "Allocation Decider" Framework; which already rules out nodes which should not even be considered for allocation or rebalance. Deciders filter out ineligible nodes. Constraints deprioritize less preferred nodes.

Yes, I agree. Also, defining priority of multiple constraint will be difficult and need more brainstorming. 

>Finally, I think it makes sense to extend the framework to handle rebalances. I did play around with it at the time, but threw it away, since allocation was the only problem we were solving then. Looks like now is a good time to add it.
If you add constraint handling to rebalances, would it take care of the extra rebalances you pointed out @dreamer-89 ?

Yes, I added the constraint in weight calculation during rebalancing. Sorry, I was not clear. With *extra rebalances* - I meant extra relocations compared to existing world where primary and replicas are equal. With proposal here, we need to move primary to attain primary balance followed by another relocation such that weight diff b/w any two nodes is within threshold (default `1.0f`).
