### ISSUE TITLE
[Searchable Snapshot] Cache path not deleted after index is deleted

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#6532]
**Describe the bug**
A path in the file system is created to store the cached blocks for a searchable snapshot index, such as:

```
data-2.x/nodes/0/cache/0/8hJW-teFRruFwKyEB4-_aA/0/RemoteLocalStore
```

When the index with ID `8hJW-teFRruFwKyEB4-_aA` is deleted I expect the `data-2.x/nodes/0/cache/0/8hJW-teFRruFwKyEB4-_aA` path to be removed, but it is not. All the contents of that directory are deleted, but the directory itself is leaked.

**To Reproduce**
Create a searchable snapshot index, then delete it.

**Expected behavior**
Assuming there are no searchable snapshot indexes in my cluster, I expect the `data-2.x/nodes/0/cache/0` directory to be empty.

**Comment by harshjain2** [comment]
@andrross Please assign this issue to me. I have started working on this issue.

**Comment by kotwanikunal** [comment]
@harshjain2 I have assigned the issue to you.

**Comment by harshjain2** [comment]
@kotwanikunal Thanks for assigning this issue. I have started working on this issue.

**Comment by harshjain2** [comment]
@andrross @kotwanikunal I am able to find the code fix. For testing the issue, I am not able to repro the issue. I tried the following steps:
1. https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/searchable_snapshot/ Followed this configuration.
2. https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore/#shared-file-system
3. ./gradlew run

After that I tried to test the OpenSearch service on local machine.

Request :
```
POST localhost:9200/_snapshot/my-fs-repository/
{
  "type": "fs",
  "settings": {
    "location": "/Users/harshjai/Desktop/opensearch/snapshot/snapshot2"
  }
}
```

Response :
```
{
	"error": {
		"root_cause": [
			{
				"type": "repository_exception",
				"reason": "[my-fs-repository] location [/Users/harshjai/Desktop/opensearch/snapshot/snapshot2] doesn't match any of the locations specified by path.repo"
			}
		],
		"type": "repository_exception",
		"reason": "[my-fs-repository] failed to create repository",
		"caused_by": {
			"type": "repository_exception",
			"reason": "[my-fs-repository] location [/Users/harshjai/Desktop/opensearch/snapshot/snapshot2] doesn't match any of the locations specified by path.repo"
		}
	},
	"status": 500
}
```

I have tried everything I can do, but find a solution to this issue. Can you please help me out with this issue.

**Comment by kotwanikunal** [comment]
@harshjain2 Can you try passing in the repo link as follows - 
`./gradlew run -Dtests.opensearch.path.repo=/Users/harshjai/Desktop/opensearch/snapshot/snapshot2`

**Comment by harshjain2** [comment]
@anasalkouz I have the fix ready, but I couldn't test it out. I can attempt fixing it by Sunday, 25th March. In case someone else is interested in picking this up, feel free to re-assign to the interested ones.

**Comment by kotwanikunal** [comment]
@harshjain2 Thanks for testing it out. Can you check if the index is in a green state i.e the shards are assigned?
You can do that by using the following API - `GET http://localhost:9200/_cat/shards`

I think you might be missing the `search` role on the node that you are testing. 
If you are testing locally, I would suggest using integration tests because of the required config by the nodes. 
This class hosts the tests for searchable snapshots and you can extend this function to run your tests - https://github.com/opensearch-project/OpenSearch/blob/879ade758668c81d29476f38afb022dd338a1048/server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java#L544-L580
In the meanwhile, feel free to create a draft PR and we can work this out on the PR.
