### ISSUE TITLE
Add circuit breaker on heap memory usage for file cache

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/OpenSearch#6540]
Coming from #6227 
Implement a circuit breaker to prevent the file cache for searchable snapshot causing an `OutOfMemoryError`. The breaker will put a limit on the cache for how much memory it can use. CircuitBreakerException will be thrown for requests that will cause the cache to use more heap memory than specified.

**Comment by kotwanikunal** [comment]
Two possible solutions were assessed - 
1. Add a new [child memory breaker](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/breaker/ChildMemoryCircuitBreaker.java#L48) which will keep track of memory usage by the file cache
2. Use a pre-existing child breaker to keep track of total memory usage (tracked by the parent breaker)

Approach 1 would be ideal if there was a fixed size of an entry for the cache, but it varies depending on the platform architecture, OS, JVM variations. 
Approach 2 solves the problem by keeping tracking of total memory usage instead of individual entries, and checking the breaker as soon as an entry is added.
