### ISSUE TITLE
[CI/CD] Test failure in GeoHashGridIT#testMultivaluedGeoPointsAggregation

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#7101]
**Describe the bug**
Caught on PR #7094 `GeoHashGridIT#testMultivaluedGeoPointsAggregation` reproducibly fails.

**To Reproduce**

```
./gradlew ':modules:geo:internalClusterTest' --tests "org.opensearch.geo.search.aggregations.bucket.GeoTileGridIT.testMultivaluedGeoPointsAggregation" -Dtests.seed=73A6EB980B2F13B4 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=is -Dtests.timezone=Africa/Addis_Ababa -Druntime.java=19
```

**Expected behavior**
Passing test

**Comment by navneet1v** [comment]
@nknize will look into this. This is really interesting to see GeoPoints Aggregation Tests getting failed. Will see if there were some changes in the tests that lead to this failure. because these tests are written when OS got forked from ES.

**Comment by navneet1v** [comment]
@nknize I found out the issue and will be raising the PR soon. The issue was happening mainly because of the way we encode the GeoPoint and error that comes in the precision due to that encoding. The error was happening for a tile: 13/1627/7465

The idea to fix this is simple enough, while generating the expected buckets for geo-points I will encode and decode the lat-lon values. This will make sure that the precision loss comes in during the Tile creation, as showed in the below snippet. 

I just have 1 question, should I do this for GeoHex also? I think I should, but need your input here.

Code ref: https://github.com/opensearch-project/OpenSearch/blob/9386cde55a55d8b4779a0c58ba9a6240d04cbe2c/modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/GeoTileGridIT.java#L161

```
protected Set<String> generateBucketsForGeoPoint(final GeoPoint geoPoint) {
        Set<String> buckets = new HashSet<>();
        for (int precision = GEOPOINT_MAX_PRECISION; precision > 0; precision--) {
            final String tile =
                    GeoTileUtils.stringEncode(GeoEncodingUtils.decodeLongitude(GeoEncodingUtils.encodeLongitude(geoPoint.getLon())), GeoEncodingUtils.decodeLatitude(GeoEncodingUtils.encodeLatitude(geoPoint.getLat())), precision);
            buckets.add(tile);
        }
        return buckets;
    }
```

**Comment by navneet1v** [comment]
> I just have 1 question, should I do this for GeoHex also? I think I should, but need your input here.

On doing some more deep-dive what I can see is this encoding of geo points to long values is already happening as part of creating Geohash for a geo-point. Hence the issue will not happen for Geohash buckets and not required for GeoHashAggregationIT.

Code reference:
https://github.com/opensearch-project/OpenSearch/blob/8394f541bc50c1f216b298e0680398a62a3fb9c9/libs/geo/src/main/java/org/opensearch/geometry/utils/Geohash.java#L298

https://github.com/opensearch-project/OpenSearch/blob/8394f541bc50c1f216b298e0680398a62a3fb9c9/libs/geo/src/main/java/org/opensearch/geometry/utils/Geohash.java#L376-L381

https://github.com/opensearch-project/OpenSearch/blob/8394f541bc50c1f216b298e0680398a62a3fb9c9/libs/geo/src/main/java/org/opensearch/geometry/utils/Geohash.java#L384-L389

**Encoding of geo-points in lucene just before storing the points:**
https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/geo/GeoEncodingUtils.java#L58-L64

**Comment by navneet1v** [comment]
PR for the fix: https://github.com/opensearch-project/OpenSearch/pull/7166

@nknize

**Comment by navneet1v** [comment]
PR is merged. Resolving the issue.
