### ISSUE TITLE
Update default shard count

### ISSUE THREAD

**Issue by lksnyder0** [opensearch-project/OpenSearch#7315]
**Is your feature request related to a problem? Please describe.**
For most use cases, a single shard is the most efficient approach. However, the current default is five. By having a default of five, we require new users to understand sharding and how the number of shards affects performance and then to know how to change the shard count

**Describe the solution you'd like**
New users can be given a better experience by changing the default shard count to 1.

**Describe alternatives you've considered**
None.

**Additional context**
This problem was discussed in a [slack thread](https://opensearch.slack.com/archives/C04UTNM338A/p1682467692632089).

**Comment by kkhatua** [comment]
@lksnyder0 
this already exists 
https://github.com/opensearch-project/OpenSearch/blob/2f411883677bbffa1bd2e0192ca36f93cddafa66/server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java#LL210C78-L210C78

You need to override as a system variable when spinning up an instance. 

If you are looking to change this dynamically, that is not going to be high priority. Index templates is one workaround, because different indices might have different usecases and data volume.

**Comment by dbwiddis** [comment]
> For most use cases, a single shard is the most efficient approach.

This may be the case for small indices, but there's also a max recommended shard size, and too-big-shards is potentially a worse problem than too-many-shards.

Since this feature already exists I'm closing this issue.  Feel free to re-open if you think the existing capability does not answer your feature request.
