### ISSUE TITLE
[Concurrent Segment Search] ContextIndexSearch handles CollectionTerminatedException

### ISSUE THREAD

**Issue by yigithub** [opensearch-project/OpenSearch#7438]
ContextIndexSearch `searchLeaf` method seems to return instead of continuing when it hits the CollectionTerminatedException.  

Ref: https://github.com/opensearch-project/OpenSearch/blob/74788c3f45895a90d030b2434539beac7a1b1723/server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java#L323

**Comment by jed326** [comment]
This looks like the right behavior to me.

https://github.com/opensearch-project/OpenSearch/blob/828730f23377e78dd1df0fa53939ed7f2486800e/server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java#L281-L345

There's no return in the `catch` blocks on L317 and L336 because those are in the if/else blocks and would not make a difference. In fact IntelliJ probably marks those returns as unnecessary and prompts the user to remove them.

 @yigithub @sohami I think we can close out this issue?
