### ISSUE TITLE
[Remote Store] Persist StoreFileMetadata fields in Remote Store

### ISSUE THREAD

**Issue by Bukhtawar** [opensearch-project/OpenSearch#7722]
**Is your feature request related to a problem? Please describe.**
We need to capture the Lucene version of the segment files maintained on the remote store to support version currency and compatibility checks.

**Describe the solution you'd like**
Consider capturing the metadata information while persisting segments to remote store
https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/store/StoreFileMetadata.java

**Describe alternatives you've considered**

**Additional context**

**Comment by BhumikaSaini-Amazon** [comment]
I was looking into this and wanted to get some additional clarity on the expected end result.

Do we want to associate the Lucene version with:
1. Each uploaded metadata file? 
2. OR, Each uploaded segment file?

(additional thoughts below)

---

If 1,

If we want to associate the Lucene version with each uploaded metadata file, we may be able to retrieve it using the segment metadata structure that exists today.

As part of `RemoteSegmentMetadata`, we persist the `SegmentInfos` bytes (i.e. `RemoteSegmentMetadata.segmentInfosBytes`) as well to remote store:

https://github.com/opensearch-project/OpenSearch/blob/4b4d84e0bc663f8374ee63aea6dab4b8b159bf5b/server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadata.java#L93-L107

The Lucene version can be retrieved as `SegmentInfos.getCommitLuceneVersion()` in this case ([docs](https://lucene.apache.org/core/9_1_0/core/org/apache/lucene/index/SegmentInfos.html#:~:text=O(N)%20cost-,getCommitLuceneVersion,-public%C2%A0Version)).

---

If 2,

If we want to associate the Lucene version with each uploaded segment, we would need to associate the Lucene version with each `UploadedSegmentMetadata`. 

While the `SegmentInfos` instance is available is available in `RemoteSegmentStoreDirectory#uploadMetadata()`...

https://github.com/opensearch-project/OpenSearch/blob/4b4d84e0bc663f8374ee63aea6dab4b8b159bf5b/server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java#L447-L494

... we actually need access to it during the actual segment file upload...

https://github.com/opensearch-project/OpenSearch/blob/4b4d84e0bc663f8374ee63aea6dab4b8b159bf5b/server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java#L514-L523

... because as part of the upload, we also construct the `UploadedSegmentMetadata` available in remote store:

https://github.com/opensearch-project/OpenSearch/blob/4b4d84e0bc663f8374ee63aea6dab4b8b159bf5b/server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java#L417-L418

I will need to work on identifying a good way to achieve this, if option 2 is the preferred end result.

---

Thanks!

**Comment by sachinpkale** [comment]
This would be due to the backward compatibility that is maintained across major Lucene versions (at most 1). So, it is possible that one metadata file will refer to segment files from different versions. So, we have to go with Option 2.

**Comment by BhumikaSaini-Amazon** [comment]
Thanks Sachin for the inputs! I will work on option 2 then.

**Comment by ankitkala** [comment]
I agree with @sachinpkale, we need version for each segment file as part of the metadata. Backwards compatibility can be a concern since you can have older segments in an index which were written on older lucene versions(e.g. version upgrade).

**Comment by Bukhtawar** [comment]
For version upgrades we just need the min version in the commit. However in future it might help to selectively upgrade fewer segments as needed.
