### ISSUE TITLE
regexp “@” matches with everything

### ISSUE THREAD

**Issue by rahul7822** [opensearch-project/OpenSearch#7858]
_- OpenSearch 1.3_
query in the opensearch “dev_tools” is as below, it’s matches with everything

```
{
  "query": {
    "bool": {
      "must": [
        {
          "regexp": {
            "search_field.keyword": "@"
          }
        }
      ]
    }
  }
}
```

Additionally below query also matches with everything
```
{
  "query": {
    "bool": {
      "must": [
        {
          "regexp": {
            "search_field.keyword": ".*&.*"
          }
        }
      ]
    }
  }
}
```

Could someone explain why It’s returning everything in the above two scenarios.
Any suggestion to improve the query with explanation will be appreciated.
Have anyone faced such type problems in opensearch?

**Comment by macohen** [comment]
Hi @rahul7822. Thanks for opening an issue: Regular expressions in OpenSearch follow Lucene's slightly non-standard syntax, which you can find here: https://lucene.apache.org/core/9_6_0/core/org/apache/lucene/util/automaton/RegExp.html.

So "@" in Lucene regex syntax means the same as ".*" which is why in my tests as well, all documents are returned.
"&" creates an intersection between two expressions so ".*&.*" finds the intersection between ".*" and ".*" which is ".*"

I hope that helps. Please reopen this issue if you have more questions.
