### ISSUE TITLE
`unknown setting [opensearch_security.*`

### ISSUE THREAD

**Issue by denysvitali** [opensearch-project/OpenSearch#804]
**Description of the issue**

According to [this page](https://docs-beta.opensearch.org/docs/security/configuration/configuration/) (docs-beta), the `opensearchproject/opensearch:1.0.0-beta1` should accept the following options:

```
opensearch_security:
  dynamic:
    http:
      ...
    authc:
      ...
    authz:
      ...
```

Due to a missing renaming of the options (or due to the fact that we're using in the `opensearchproject/opensearch:1.0.0-beta1` image the OpenDistro security plugin), this results in the following OpenSearch error if one of those options (e.g: `opensearch_security.ssl.transport.keystore_filepath`) being used:

```
Caused by: java.lang.IllegalArgumentException: unknown setting [opensearch_security.ssl.transport.keystore_filepath] did you mean any of [opendistro_security.ssl.
transport.keystore_filepath, opendistro_security.ssl.transport.truststore_filepath, opendistro_security.ssl.transport.pemcert_filepath, opendistro_security.ssl.tr
ansport.keystore_alias, opendistro_security.ssl.transport.keystore_type, opendistro_security.ssl.transport.pemkey_filepath, opendistro_security.ssl.transport.keys
tore_password, opendistro_security.ssl.http.keystore_filepath, opendistro_security.ssl.transport.pemtrustedcas_filepath, opendistro_security.ssl.transport.keystor
e_keypassword]?
```

**To Reproduce**

```bash
docker run --rm -e 'opensearch_security.ssl.transport.keystore_filepath=/tmp/test.jks' opensearchproject/opensearch:1.0.0-beta1
```

**Expected behavior**

The option should be accepted and the user shouldn't use `opendistro_security` to work around the issue

**Plugins**

- `opensearch-security-1.0.1.0` ?

---

Unfortunately it's still unclear to me how the `opensearchproject/opensearch:1.0.0-beta1` image was created as I haven't found any CI related to the project and the image seems to have been pushed (manually?) by @peterzhuamazon

**Comment by dblock** [comment]
I think this issue belongs in https://github.com/opensearch-project/security.

I see a bunch of beta1 tags in security, and I am not sure which one was the actual beta1 build, cc: @vrozov that can maybe help clean this up and clarify what's what.

<img width="287" alt="Screen Shot 2021-06-01 at 10 39 00 AM" src="https://user-images.githubusercontent.com/542335/120342261-9fc89280-c2c5-11eb-83ff-bde87ba04a52.png">

It does look like settings renaming happened _after_ beta1 in https://github.com/opensearch-project/security/pull/1176, which explains this error. It has been fixed by rc1. I'll close this since it's "as designed". Please let us know if you see more issues!
