### ISSUE TITLE
[Remote Translog] Understand impact of high translog upload buffer interval

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#8189]
**Is your feature request related to a problem? Please describe.**
We support buffering translog sync/upload with remote translog enabled. This means that the sync/upload happens every periodic interval and if the durability mode is `REQUEST`, it would lead to the client waiting for the response until the buffer interval has elapsed and then request has been processed. We need to understand if there are cases where high buffer interval is required or we can have upper limit as well for the buffer interval.

**Describe the solution you'd like**
Understand the maximum buffer interval that makes sense and impose a max limit on the same.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by gbbafna** [comment]
[Storage Triage] - Attendees [1](https://github.com/ltaragi) [2](https://github.com/reta) [3](https://github.com/skumawat2025) [4](https://github.com/gbbafna) [5](https://github.com/linuxpi)

I am not sure there is anything actionable on this right now since buffer interval is already configurable. Feel free to reopen in case you have any other ideas.
