### ISSUE TITLE
Enable deployment without security enabled

### ISSUE THREAD

**Issue by mkbhanda** [opensearch-project/OpenSearch#861]
**Is your feature request related to a problem? Please describe.**
OpenSearch has security on by default while in Elastic Search it was off by default.
Security on is a good default but for non-production deployments, would be nice to be able to turn it off.

**Describe the solution you'd like**
Adding documentation and support to turn off security would help users who seek to migrate with such use cases. 

**Describe alternatives you've considered**
Would need to set up some self signed certificates for test deployment. Antrea a CNCF sandbox's project for Kubernetes networking using open VSwitch was originally using ELK without security. 

**Additional context**

**Comment by dblock** [comment]
Disabling security is [documented here](https://docs-beta.opensearch.org/security-plugin/configuration/disable/). Generally we'd like to have good defaults for non-production deployments *with* security enabled so that it's not in the way. Appreciate any comments of what that could look like for your scenarios.

I'll close this since we do have docs as asked, but feel free to add comments or reopen if that's insufficient.
