### ISSUE TITLE
[BUG] [Remote Store] Retry file downloads during failures

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#8885]
Coming from discussion in https://github.com/opensearch-project/OpenSearch/pull/8767#discussion_r1272217909, on failures during file downloads, [IndexShardRecoveryException](https://github.com/opensearch-project/OpenSearch/blob/3ee42920fa886bdf566f1bb7b1666ffa72d36f54/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L4757) is thrown during recovery and replication is marked [failed](https://github.com/opensearch-project/OpenSearch/blob/3ee42920fa886bdf566f1bb7b1666ffa72d36f54/server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java#L493) during round of segment replication. For retryable errors, the file download should be retried.

**Comment by anasalkouz** [comment]
@kotwanikunal is this related to multipart download? are you actively working on it?

**Comment by kotwanikunal** [comment]
> @kotwanikunal is this related to multipart download? are you actively working on it?

It is related to the remote store downloads. But I am incorporating it as a part of the multistream download mechanism.

**Comment by kotwanikunal** [comment]
Considering this as a separate issue from multi stream since the work is still in progress and this might be a necessary feature for downloads in general

**Comment by sachinpkale** [comment]
I am removing the 2.10 tag for this task. We need to think more on where exactly we need to add the retry logic. For example, it is better to add retry at BlobContainer/BlobStore level so that any download (segment/translog/metadata) will go through the same logic.

Also, some of the existing implementations already has implemented the retry logic: 
- [GCP](https://github.com/opensearch-project/OpenSearch/blob/main/plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageBlobStore.java#L222)
- [S3](https://github.com/opensearch-project/OpenSearch/blob/main/plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java#L139)

**Comment by sachinpkale** [comment]
Retry logic needs to be implemented at the repository plugin implementation. Closing it as `Not Required`
