### ISSUE TITLE
[Streaming Indexing] Introduce bulk HTTP API streaming flavour

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#9070]
**Is your feature request related to a problem? Please describe.**
The `bulk` HTTP API does not support streaming (neither HTTP/2 nor chunked transfer)

**Describe the solution you'd like**
Introduce bulk HTTP API streaming flavor based on new experimental transport (https://github.com/opensearch-project/OpenSearch/issues/9067)

**Describe alternatives you've considered**
N/A

**Additional context**
See please https://github.com/opensearch-project/OpenSearch/issues/9067

**Comment by reta** [comment]
There is new experimental API introduced in `2.15.0` which is not yet documented nor finalized:

```
    POST  /_bulk/stream
    PUT    /_bulk/stream
    POST  /{index}/_bulk/stream
    PUT    /{index}/_bulk/stream
```

The new API is using LD-JSON and at the moment, picks a single chunk from the stream (bulk operation), forwards it to the node of the cluster and returns the result of the operation as a chunk in the response, for example the request with three chunks:

```
<---- chunk 1 -----> 
{ "index": { "_index": "test-streaming", "_id": "1" } }
{ "name": "josh" }
<---- chunk 1 -----> 

<---- chunk 2 -----> 
{ "index": { "_index": "test-streaming", "_id": "2" } }
{ "name": "tom" }
<---- chunk 2 -----> 

<---- chunk 3 -----> 
{ "index": { "_index": "test-streaming", "_id": "3" } }
{ "name": "john" }
<---- chunk 3 -----> 

```

would receive a response with three chunks as well (1:1):

```
<---- chunk 1 -----> 
{"took":547,"errors":false,"items":[{"index":{"_index":"test-streaming","_id":"1","_version":1,"result":"created","forced_refresh":true,"_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}}]}

<---- chunk 2 -----> 
{"took":20,"errors":false,"items":[{"index":{"_index":"test-streaming","_id":"2","_version":1,"result":"created","forced_refresh":true,"_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1,"_primary_term":1,"status":201}}]}
<---- chunk 2 -----> 

<---- chunk 3 -----> 
{"took":22,"errors":false,"items":[{"index":{"_index":"test-streaming","_id":"3","_version":1,"result":"created","forced_refresh":true,"_shards":{"total":2,"successful":1,"failed":0},"_seq_no":2,"_primary_term":1,"status":201}}]}
<---- chunk 3 -----> 
```

This is simple communication model but very inefficient. The goal of this issue is to formalize API in such a way that it could be used as efficiently as possible, aiming to overtake existing `/_bulk` APIs in the future.

**Comment by reta** [comment]
@andrross @dblock @msfroh would appreciate early feedback if possible, working in some POCs at the moment to capture the operational metrics.

**Comment by andrross** [comment]
@reta My inclination here is that since this is a new API that is specifically targeting high-throughput use cases then we should explore option 2. I think there is quite a lot of overhead with parsing JSON and a binary protocol could improve upon that. For simple use cases where ease of use is paramount, the existing request-response style newline delimited JSON API will remain. I also think we could make adoption for the end user easier by making minimal changes to the public API of the various language clients like opensearch-java by continuing to use the current types exposed by those APIs even if it means an extra conversion on the client side to say a protobuf object type in the process of doing the binary serialization.

Tagging @amberzsy here as she is working on some protobuf experiments with the client API on the search side. We could potentially make the protobuf implementation for the client API much easier by generating the protobuf schemas from the opensearch-api specification, as that should the source-of-truth for OpenSearch client API.

**Comment by reta** [comment]
> @reta My inclination here is that since this is a new API that is specifically targeting high-throughput use cases then we should explore option 2.

Thanks @andrross , I will try this route as well and publish some metrics so we could compare the wins (if any), thanks!

**Comment by andrross** [comment]
@reta I'm really curious if the protobuf `Any` type is feasible here. Have you actually used it in practice at all? I was thinking we might have to fallback to binary blobs of UTF-8 encoded JSON for the actual document source in some cases.

**Comment by reta** [comment]
> @reta I'm really curious if the protobuf `Any` type is feasible here. Have you actually used it in practice at all? I was thinking we might have to fallback to binary blobs of UTF-8 encoded JSON for the actual document source in some cases.

No, I haven't tried this schema yet in practice (only made sure it is processable by `protoc` successfully), will let you know how it goes, thanks @andrross !

**Comment by reta** [comment]
To have change delivered incrementally, focusing this issue on HTTP/NDJSON API flavour (Option `#1`) and spinning off https://github.com/opensearch-project/OpenSearch/issues/15447 for future release (Option `#2`).
