### ISSUE TITLE
[Remote Store] BlobStore used in Remote Store doesn't use updated settings and repo metadata  

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/OpenSearch#9118]
**Describe the bug**

For RemoteStore, once we create `BlobStore` , we don't close it ever and reuse it for nodes' lifetime. That means the plugin level settings and repo metadata update doesn't get applied to it . 

There are two issues which we need to fix here : 

1. When we update repository, Repositories Service closes existing `BlobRepository` , `BlobStore` and opens a new one . However `RemoteStore` continues to use existing `BlobStore` which has no clue on new metadata .

1. We never `reload` the BlobStoreRepository in place. This means that cluster settings update also doesn't get applied on repo. 

 
We need to a way to update the Remote Repositories in place, so that updated settings and repo metadata is reflected . 

**Expected behavior**

**Comment by BhumikaSaini-Amazon** [comment]
@gbbafna I was looking at the S3 implementation. In my understanding, the following values shouldn't be reloadable because that could possibly break things in the remote store flows:

https://github.com/opensearch-project/OpenSearch/blob/2a5b124ee8ef4376d62c484b6cd3ea1d98ca75d1/plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java#L260-L313

Is there a known use case where we want these too to be reloadable?

Thanks!

**Comment by gbbafna** [comment]
Hi @BhumikaSaini-Amazon , Currently these are also reloadable. However we are restricting changing these for system repositories : https://github.com/opensearch-project/OpenSearch/pull/9839/ . 

For snapshot changing the path does work - it just works like snapshot repository is cleaned up and you start from scratch .
