### ISSUE TITLE
[Concurrent Segment Search] Functional test coverage

### ISSUE THREAD

**Issue by sohami** [opensearch-project/OpenSearch#9468]
**Describe the solution you'd like**
This is a tracking issue to verify functionality of the concurrent segment search other than Java IT tests which is being enabled as part of separate issue https://github.com/opensearch-project/OpenSearch/issues/7440

We can use r5.xlarge instance type for below:

1. Run all the OSB workloads with concurrent segment search enabled, slice count of 0 and multiple client say 2 or 4. With each run ensure there is no error or failures during the execution and results are correct and same as concurrent search disabled.
2. Perform reindex operation with concurrent segment search enabled. As part of reindex first documents are queried from source index and then indexed into a target index. This will catch any issues with querying the documents using concurrent segment search.
3. Run few OSB workloads with concurrent segment search enabled and on SegRep enabled indices and verify i) the results are same as doc rep enabled indices ii) no failures are seen during the run with seg rep indices. For this we will need multi-node setup with replicas such that search can happen over replicas too.

**Comment by neetikasinghal** [comment]
i am working on this

**Comment by neetikasinghal** [comment]
<h1 style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">Functional Testing for Concurrent Search</h1><h2 style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">Overview</h2><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -webkit-standard; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">As part of functional testing for concurrent search, we need to validate that the different search operations are working as<span class="Apple-converted-space"> </span></span><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -webkit-standard; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">is without any regression. In order to ensure that, the tests are run across the following workloads:</span><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -webkit-standard; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">Different workloads in opensearch benchmarking (ref:<span class="Apple-converted-space"> </span></span><a href="https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">link</a><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -webkit-standard; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">):</span><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><ul style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><li><a href="https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/eventdata">eventdata</a><span class="Apple-converted-space"> </span>- only has indexing bulk operation</li><li><a href="https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/geonames"><span textcolor="#1f2328" style="--original-color: #1f2328; color: rgb(31, 35, 40);">geonames</span></a><span class="Apple-converted-space"> </span>- search focused</li><li><a href="https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/geopoint">geopoint</a><span class="Apple-converted-space"> </span>- search focused</li><li><a href="https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/geopointshape">geopointshape</a><span class="Apple-converted-space"> </span>- search</li><li><a href="https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/geoshape">geoshape</a><span class="Apple-converted-space"> </span>- search</li><li><a href="https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/http_logs">http_logs</a><span class="Apple-converted-space"> </span>- has assertions</li><li><a href="https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/nested">nested</a><span class="Apple-converted-space"> </span>- search</li><li><a href="https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/noaa">noaa</a><span class="Apple-converted-space"> </span>- search</li><li><a href="https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/nyc_taxis">nyc_taxis</a><span class="Apple-converted-space"> </span>- search</li><li><a href="https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/percolator">percolator</a><span class="Apple-converted-space"> </span>- search</li><li><a href="https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/pmc">pmc</a><span class="Apple-converted-space"> </span>- search</li><li><a href="https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/so">so</a><span class="Apple-converted-space"> </span>- only has indexing bulk operation</li></ul><h2 style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">Cluster creation</h2><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -webkit-standard; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">Following three clusters are created with the help of<span class="Apple-converted-space"> </span></span><code style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">opensearch-cluster-cdk</code><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -webkit-standard; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">:<span class="Apple-converted-space"> </span></span><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><ul style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><li>Opensearch cluster with concurrent search enabled and slice count of 0</li><li>Opensearch cluster with concurrent search enabled and slice count of 1</li><li>Opensearch cluster with concurrent search disabled</li></ul><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -webkit-standard; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">Create cluster command:</span><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><pre style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">cdk deploy "*" \<br>--context region=$REGION \<br>--context securityDisabled=true \<br>--context minDistribution=$MIN_DISTRIBUTION \<br>--context distributionUrl=$DISTRIBUTION_URL \<br>--context cpuArch=$CPUARCH \<br>--context singleNodeCluster=$SINGLENODE \<br>--context distVersion=$DISTRO \<br>--context serverAccessType=$ACCESSTYPE \<br>--context restrictServerAccessTo=$ACCESS_PREFIX \<br>--context dataInstanceType=$INSTANCE_TYPE \<br>--context storageVolumeType=$STORAGE_VOL_TYPE \<br>--context dataNodeStorage=$STORAGE_SIZE \<br>--context use50PercentHeap=true \<br>--context suffix=$SUFFIX \<br>--context additionalConfig=$ADDITIONAL_CONFIG</pre><h2 style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">Data ingestion</h2><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -webkit-standard; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">On every cluster the benchmarking is run for all the workloads as follows:</span><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -webkit-standard; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">Cluster 1: neetiks-1-cs-enabled-slice0</span><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><code style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">opensearch-infra-stack-neetiks-1-cs-enabled-slice0.loadbalancerurl =<span class="Apple-converted-space"> </span><a href="http://opens-clust-g2vsvrha3ev6-a370faf942d5a688.elb.us-east-1.amazonaws.com/">opens-clust-G2VSVRHA3EV6-a370faf942d5a688.elb.us-east-1.amazonaws.com</a></code><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><code style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">opensearch-infra-stack-neetiks-1-cs-enabled-slice0.privateip = 10.0.3.176</code><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><pre style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">MIN_DISTRIBUTION=true<br>DISTRIBUTION_URL=https://artifacts.opensearch.org/snapshots/core/opensearch/2.10.0-SNAPSHOT/opensearch-min-2.10.0-SNAPSHOT-linux-x64-latest.tar.gz<br>CPUARCH='x64'<br>SINGLENODE=true<br>HEAP50PCT=true<br>SUFFIX='neetiks-1-cs-enabled-slice0'<br>ACCESSTYPE='prefixList'<br>ACCESS_PREFIX='pl-4e2ece27'<br>DISTRO='2.10.0'<br>INSTANCE_TYPE=r5.8xlarge<br>ADDITIONAL_CONFIG='{"opensearch.experimental.feature.concurrent_segment_search.enabled": "true", "search.concurrent.max_slice_count": "0"}'<br>STORAGE_SIZE=1000<br>STORAGE_VOL_TYPE='gp3</pre><pre style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">#!/bin/sh<br>array=(<br>  nyc_taxis<br>  geonames<br>  geopoint<br>  geopointshape<br>  geoshape<br>  nested<br>  noaa<br>  percolator<br>  pmc<br>  http_logs<br>)<br><br>for index in ${!array[*]}; do<br>  opensearch-benchmark execute-test \<br>    --workload-params="target_throughput:none,number_of_replicas:0,number_of_shards:1,search_clients:2" \<br>    --user-tag="testcase:functional-cs-enabled-slice-0,arch:x86,instance:r5.large,cs_enabled:true,slice_count:0,num_shards:1,shard_size:default,num_replicas:0,node_count:1,client_count:2,search_threadpool:default" \<br>    --target-hosts 'http://opens-clust-G2VSVRHA3EV6-a370faf942d5a688.elb.us-east-1.amazonaws.com:80' \<br>    --pipeline=benchmark-only \<br>    --telemetry=node-stats \<br>    --kill-running-processes \<br>    --workload-path=/home/ec2-user/.benchmark/benchmarks/workloads/default/${array[$index]} \<br>    --enable-assertions<br>  sleep 60<br>done</pre><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -webkit-standard; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">Cluster 2: neetiks-1-cs-enabled-slice1</span><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><code style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">opensearch-infra-stack-neetiks-1-cs-enabled-slice1.loadbalancerurl =<span class="Apple-converted-space"> </span><a href="http://opens-clust-apv877f3fai9-e0e9adc39546e8ee.elb.us-east-1.amazonaws.com/">opens-clust-APV877F3FAI9-e0e9adc39546e8ee.elb.us-east-1.amazonaws.com</a></code><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><code style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">opensearch-infra-stack-neetiks-1-cs-enabled-slice1.privateip = 10.0.3.158</code><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><pre style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">MIN_DISTRIBUTION=true<br>DISTRIBUTION_URL=https://artifacts.opensearch.org/snapshots/core/opensearch/2.10.0-SNAPSHOT/opensearch-min-2.10.0-SNAPSHOT-linux-x64-latest.tar.gz<br>CPUARCH='x64'<br>SINGLENODE=true<br>HEAP50PCT=true<br>SUFFIX='neetiks-1-cs-enabled-slice1'<br>ACCESSTYPE='prefixList'<br>ACCESS_PREFIX='pl-4e2ece27'<br>DISTRO='2.10.0'<br>INSTANCE_TYPE=r5.8xlarge<br>ADDITIONAL_CONFIG='{"opensearch.experimental.feature.concurrent_segment_search.enabled": "true", "search.concurrent.max_slice_count": "1"}'<br>STORAGE_SIZE=1000<br>STORAGE_VOL_TYPE='gp3'</pre><pre style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">#!/bin/sh<br>array=(<br>  nyc_taxis<br>  geonames<br>  geopoint<br>  geopointshape<br>  geoshape<br>  nested<br>  noaa<br>  percolator<br>  pmc<br>  http_logs<br>)<br><br>for index in ${!array[*]}; do<br>  opensearch-benchmark execute-test \<br>    --workload-params="target_throughput:none,number_of_replicas:0,number_of_shards:1,search_clients:2" \<br>    --user-tag="testcase:functional-cs-enabled-slice-1,arch:x86,instance:r5.large,cs_enabled:true,slice_count:1,num_shards:1,shard_size:default,num_replicas:0,node_count:1,client_count:2,search_threadpool:default" \<br>    --target-hosts 'http://opens-clust-APV877F3FAI9-e0e9adc39546e8ee.elb.us-east-1.amazonaws.com:80' \<br>    --pipeline=benchmark-only \<br>    --telemetry=node-stats \<br>    --kill-running-processes \<br>    --workload-path=/home/ec2-user/.benchmark/benchmarks/workloads/default/${array[$index]} \<br>    --enable-assertions<br>  sleep 60<br>done</pre><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -webkit-standard; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">Cluster 3: neetiks-1-cs-disabled</span><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><code style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">opensearch-infra-stack-neetiks-2-cs-disabled.loadbalancerurl =<span class="Apple-converted-space"> </span><a href="http://opens-clust-p2uzsmzuwf1s-206fcfd42be83165.elb.us-east-1.amazonaws.com/">opens-clust-P2UZSMZUWF1S-206fcfd42be83165.elb.us-east-1.amazonaws.com</a></code><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><code style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">opensearch-infra-stack-neetiks-2-cs-disabled.privateip = 10.0.3.75</code><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><pre style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">MIN_DISTRIBUTION=true<br>DISTRIBUTION_URL=https://artifacts.opensearch.org/snapshots/core/opensearch/2.10.0-SNAPSHOT/opensearch-min-2.10.0-SNAPSHOT-linux-x64-latest.tar.gz<br>CPUARCH='x64'<br>SINGLENODE=true<br>HEAP50PCT=true<br>SUFFIX='neetiks-2-cs-disabled'<br>ACCESSTYPE='prefixList'<br>ACCESS_PREFIX='pl-4e2ece27'<br>DISTRO='2.10.0'<br>INSTANCE_TYPE=r5.8xlarge<br>STORAGE_SIZE=1000<br>STORAGE_VOL_TYPE='gp3'</pre><pre style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">#!/bin/sh<br>array=(<br>  nyc_taxis<br>  geonames<br>  geopoint<br>  geopointshape<br>  geoshape<br>  nested<br>  noaa<br>  percolator<br>  pmc<br>  http_logs<br>)<br><br>for index in ${!array[*]}; do<br>  opensearch-benchmark execute-test \<br>    --workload-params="target_throughput:none,number_of_replicas:0,number_of_shards:1,search_clients:2" \<br>    --user-tag="testcase:functional-cs-disabled,arch:x86,instance:r5.large,cs_enabled:false,slice_count:default,num_shards:1,shard_size:default,num_replicas:0,node_count:1,client_count:2,search_threadpool:default" \<br>    --target-hosts 'http://opens-clust-P2UZSMZUWF1S-206fcfd42be83165.elb.us-east-1.amazonaws.com:80' \<br>    --pipeline=benchmark-only \<br>    --telemetry=node-stats \<br>    --kill-running-processes \<br>    --workload-path=/home/ec2-user/.benchmark/benchmarks/workloads/default/${array[$index]} \<br>    --enable-assertions<br>  sleep 60<br>done</pre><h2 style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">Search validation script</h2><pre style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">import json<br>import requests<br><br>if __name__ == '__main__':<br>    fp = open("/Users/neetiks/workspace/PycharmProjects/SnapshotDelete/benchmarks/nyc_taxis_default.json", "r")<br>    index_name = "nyc_taxis"<br>    data = json.load(fp)<br><br>    slice0_url = 'http://opens-clust-G2VSVRHA3EV6-a370faf942d5a688.elb.us-east-1.amazonaws.com:80/'<br>    slice1_url = 'http://opens-clust-APV877F3FAI9-e0e9adc39546e8ee.elb.us-east-1.amazonaws.com:80/'<br>    cs_disabled_url = 'http://opens-clust-P2UZSMZUWF1S-206fcfd42be83165.elb.us-east-1.amazonaws.com:80/'<br><br>    print('dataset validation starting...')<br>    for entry in data:<br>        if entry["operation-type"] == "search":<br>            if entry.get("body") is None:<br>                continue<br>            request_body = entry["body"]<br>            search_request = index_name + "/_search?pretty"<br>            print('operation name: ' + str(entry["name"]))<br>            print('search request body : ' + str(request_body))<br><br>            # baseline response<br>            try:<br>                baseline_response = requests.post(cs_disabled_url + search_request, json=request_body, headers={"Content-Type":"application/json"})<br>                baseline_hits = json.loads(baseline_response.text)["hits"]["total"]["value"]<br>                print('baseline hits = ' + str(baseline_hits))<br><br>                # slice0 response<br>                slice0_response = requests.post(cs_disabled_url + search_request, json=request_body,<br>                                                  headers={"Content-Type": "application/json"})<br>                slice0_hits = json.loads(slice0_response.text)["hits"]["total"]["value"]<br>                print('slice 0 hits = ' + str(slice0_hits))<br>                assert baseline_hits == slice0_hits<br><br>                # slice1 response<br>                slice1_response = requests.post(cs_disabled_url + search_request, json=request_body,<br>                                                  headers={"Content-Type": "application/json"})<br>                slice1_hits = json.loads(slice1_response.text)["hits"]["total"]["value"]<br>                assert baseline_hits == slice1_hits<br>                print('slice 1 hits = ' + str(slice1_hits))<br>            except Exception as e:<br>                print('error:' + str(e))<br>    print('dataset validation complete!!')</pre><h2 style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">Results</h2>

Dataset | Assert hits | index
-- | -- | --
nyc_taxis | successful | nyc_taxis
geonames | successful | geonames
geopoint | successful | osmgeopoints
geopointshape | successful | osmgeoshapes
geoshape | successful | osmlinestrings, osmmultilinestrings, osmpolygons
nested | successful | sonested
noa | successful | weather-data-2016
percolator | successful | queries
pmc | successful | pmc
http_logs | successful | reindexed-logs, logs-181998, logs-191998, logs-201998, logs-211998, logs-221998, logs-231998, logs-241998
