### ISSUE TITLE
[BUG] Github action for gradle precommit failing on main

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/OpenSearch#9478]
**Describe the bug**
Gradle precommit is failing on main due to error below. It doesn't fail when tried on my local workspace though. 
Sample failure: https://github.com/ankitkala/OpenSearch/actions/runs/5937653411
```
Note: Recompile with -Xlint:deprecation for details.
----- End of the daemon log -----

JVM crash log found: file:///D:/a/OpenSearch/OpenSearch/hs_err_pid6888.log

FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

```

**To Reproduce**
1. Forked the main branch into a personal repository.
2. Enabled the github action on the repo & branch([example commit](https://github.com/ankitkala/OpenSearch/commit/21334cf6ec050a79a6b3fbc9760fd6ede03c1d7b)).
3. Pushed the code and monitor the gradle precommit workflow. 
Sample branch: https://github.com/ankitkala/OpenSearch/tree/archived_setting_test_control

**Expected behavior**
The gradle precommit should not fail.

**Comment by tlfeng** [comment]
It's a bug from the macOS image of GitHub Action https://github.com/actions/runner-images/issues/8104

I would rather wait GitHub Action to fix the macOS image problem, than making a fix from outside.
If necessary, we can exclude macOS from running precommit task in the workflow (https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/precommit.yml#L10).
Since Gradle "precommit" task is included in "check" task, I think we can ignore the result of "precommit" task under macOS when reviewing the PRs.
