### ISSUE TITLE
[BUG] Test RemoteFSTranslogTests.testMetadataFileDeletion is flaky

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#9605]
https://github.com/opensearch-project/OpenSearch/pull/9595#issuecomment-1696672926

**Comment by mch2** [comment]
@ashking94 Can you pls take a look at this one.

**Comment by ashking94** [comment]
Running this test on loop to reproduce this issue and accordingly decide the next step.

**Comment by ashking94** [comment]
I have been able to root cause the flakiness in this test due to `translog.trimUnreferencedReaders()` being no-op when called due to previous deletion still ongoing and holding the permits. The current run of `translog.trimUnreferencedReaders()` on checking for permits sees that there are not the required permits available and leaves the deletion. To elaborate more on generation deletion, the approach is to acquire the permits, trigger async deletion and post successful deletion, release the permits.
