### ISSUE TITLE
Include HttpClient 5.X for the rest client

### ISSUE THREAD

**Issue by AhmadMS1988** [opensearch-project/OpenSearch#9718]
I would like to see HttpClient 5.X included in the next release of the java client.
I has a great potential to solve [this](https://github.com/opensearch-project/opensearch-java/issues/545) issue, and it is already merged in main [here](https://github.com/opensearch-project/OpenSearch/pull/4459) and [here](https://github.com/opensearch-project/OpenSearch/commit/4833e080cc506237fee5aa90767d6f49d952bec3).
Is there anything preventing this from being included in the next version of the java client as it is one year old?
Thank you very much

**Comment by tlfeng** [comment]
Hi @AhmadMS1988 Are you requesting to have HttpClient 5.x in next release of [Java high-level REST client](https://opensearch.org/docs/2.9/clients/java-rest-high-level/)?
It is embedded in this repository and releases along with OpenSearch core. As your referred PR says, it is considered as a breaking change, so it can only be released along with next OpenSearch major version (3.0).
@reta Could you double check your code change https://github.com/opensearch-project/OpenSearch/commit/4833e080cc506237fee5aa90767d6f49d952bec3 of using HttpClient 5.x is a breaking change that can't be backported to 2.x branch?

I also noticed Java high-level REST client is deprecated, it's recommended switching to the [Java client](https://opensearch.org/docs/2.9/clients/java/) instead. The new "Java client" already have HttpClient 5.x in the code https://github.com/opensearch-project/opensearch-java/tree/v2.6.0/java-client/src/main/java/org/opensearch/client/transport/httpclient5 since version 2.2.0 .

**Comment by reta** [comment]
Thanks @tlfeng

> Hi @AhmadMS1988 Are you requesting to have HttpClient 5.x in next release of [Java high-level REST client](https://opensearch.org/docs/2.9/clients/java-rest-high-level/)?

The Apache HttpClient 5 based RestClient is part of the 3.0.0 release. However, if you switch to officially recommended `opensearch-java` client, you could benefit of Apache HttpClient 5 right now [1], as @tlfeng mentioned.

> @reta Could you double check your code change https://github.com/opensearch-project/OpenSearch/commit/4833e080cc506237fee5aa90767d6f49d952bec3 of using HttpClient 5.x is a breaking change that can't be backported to 2.x branch?

Yes, sadly RestClient leaked Apache HttpClient 4.x APIs (like HttpHost etc) and this is a breaking change both from API and dependency perspectives.

[1] https://github.com/opensearch-project/opensearch-java/blob/2.x/USER_GUIDE.md#create-a-client-using-apachehttpclient5transport
